/**
 * Modern CV Typst Generator
 * Single-column modern resume with clean minimalist design
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
} from '@/lib/typst/utils';

/**
 * Generate complete Modern CV Typst code
 */
export function generateModernCV(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateSummary(data.basics.summary),
    generateExperienceSection(data.work),
    generateEducationSection(data.education),
    generateProjectsSection(data.projects),
    generateSkillsSection(data.skills),
    generateAchievementsSection(data.achievements),
    generateCertificationsSection(data.certifications),
    generateReferencesSection(data.references),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with modern minimalist styling
 */
function generatePreamble(): string {
  return `// Modern CV — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 2cm, right: 2cm, top: 2cm, bottom: 2cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 11pt,
  fill: rgb("#1a1a1a"),
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette —
#let primary   = rgb("#1a1a1a")
#let accent    = rgb("#2563eb")
#let secondary = rgb("#64748b")

// — Reusable components —

#let cv-section(title) = {
  v(0.8em)
  text(size: 14pt, weight: "bold", fill: primary, upper(title))
  v(0.2em)
  line(length: 100%, stroke: 1.5pt + accent)
  v(0.4em)
}

#let cv-event(title, subtitle, date, location) = {
  v(0.3em)
  grid(
    columns: (1fr, auto),
    text(weight: "bold", fill: primary, title),
    text(size: 9pt, style: "italic", fill: secondary, date),
  )
  grid(
    columns: (1fr, auto),
    text(style: "italic", fill: secondary, subtitle),
    text(size: 9pt, fill: secondary, location),
  )
  v(0.4em)
}

#let cv-tag(keyword) = {
  box(
    inset: (x: 5pt, y: 3pt),
    radius: 3pt,
    fill: accent.lighten(90%),
    text(size: 9pt, weight: "bold", fill: accent, keyword),
  )
  h(3pt)
}

#let cv-divider() = {
  v(0.5em)
}`;
}

/**
 * Generate header with personal information
 */
function generateHeader(basics: ResumeData['basics']): string {
  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(
      `#link("mailto:${basics.email}")[${escapeTypst(basics.email)}]`
    );
  }
  if (basics.phone) {
    contactParts.push(escapeTypst(basics.phone));
  }
  if (basics.location) {
    contactParts.push(escapeTypst(basics.location));
  }

  basics.profiles?.forEach((profile) => {
    const label = profile.label || cleanURL(profile.url);
    contactParts.push(
      `#link("${profile.url}")[${escapeTypst(label)}]`
    );
  });

  const contactLine = contactParts.join('  #text(fill: secondary)[ \\~ ]  ');

  return `// ── Header ──────────────────────────────────────────
#align(center)[
  #text(size: 24pt, weight: "bold", fill: primary)[${escapeTypst(basics.name)}]
  #linebreak()
  #v(4pt)
  #text(size: 12pt, fill: secondary)[${escapeTypst(basics.label)}]
  #v(6pt)
  #text(size: 9pt, fill: secondary)[${contactLine}]
]`;
}

/**
 * Generate summary section
 */
function generateSummary(summary?: string): string {
  if (!summary) return '';

  return `#cv-section("Summary")
${escapeTypst(summary)}`;
}

/**
 * Generate work experience section
 */
function generateExperienceSection(work: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const entries = work.map((job) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);

    let content = `#cv-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

    if (job.highlights && job.highlights.length > 0) {
      content += '\n' + job.highlights.map((h) => `- ${escapeTypst(h)}`).join('\n');
    }

    content += '\n#cv-divider()';

    return content;
  });

  return `#cv-section("Work Experience")

${entries.join('\n\n')}`;
}

/**
 * Generate education section
 */
function generateEducationSection(education: ResumeData['education']): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu) => {
    const dateRange = formatDateRange(edu.startDate, edu.endDate);
    const degree = `${edu.studyType} in ${edu.area}`;

    let content = `#cv-event("${escapeTypst(degree)}", "${escapeTypst(edu.institution)}", "${dateRange}", "${escapeTypst(edu.location)}")`;

    if (edu.gpa) {
      content += `\nGPA: ${escapeTypst(edu.gpa)}`;
    }
    if (edu.note) {
      content += `\n${escapeTypst(edu.note)}`;
    }

    content += '\n#cv-divider()';

    return content;
  });

  return `#cv-section("Education")

${entries.join('\n\n')}`;
}

/**
 * Generate projects section
 */
function generateProjectsSection(projects: ResumeData['projects']): string {
  if (!projects || projects.length === 0) return '';

  const entries = projects.map((project) => {
    let header = `*${escapeTypst(project.name)}*`;
    if (project.url) {
      header = `#link("${project.url}")[*${escapeTypst(project.name)}*]`;
    }

    let content = header + ` \\ ${escapeTypst(project.description)}`;

    if (project.highlights && project.highlights.length > 0) {
      content += '\n' + project.highlights.map((h) => `- ${escapeTypst(h)}`).join('\n');
    }

    content += '\n#cv-divider()';

    return content;
  });

  return `#cv-section("Projects")

${entries.join('\n\n')}`;
}

/**
 * Generate skills section
 */
function generateSkillsSection(skills: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const groups = skills.map((skillGroup) => {
    const tags = skillGroup.keywords
      .map((kw) => `#cv-tag("${escapeTypst(kw)}")`)
      .join('\n');
    return `*${escapeTypst(skillGroup.name)}:* ${tags}`;
  });

  return `#cv-section("Skills")

${groups.join('\n\n')}`;
}

/**
 * Generate achievements section
 */
function generateAchievementsSection(achievements?: string[]): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map((a) => `- ${escapeTypst(a)}`).join('\n');

  return `#cv-section("Achievements")

${items}`;
}

/**
 * Generate certifications section
 */
function generateCertificationsSection(certifications?: string[]): string {
  if (!certifications || certifications.length === 0) return '';

  const items = certifications.map((c) => `- ${escapeTypst(c)}`).join('\n');

  return `#cv-section("Certifications")

${items}`;
}

/**
 * Generate references section
 */
function generateReferencesSection(references?: string): string {
  if (!references) return '';

  return `#cv-section("References")

${escapeTypst(references)}`;
}
