/**
 * Card Grid Layout Typst Generator
 * 50/50 layout with card-based design using bordered boxes
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from '@/lib/typst/utils';

/**
 * Generate complete Card Grid Layout Typst code
 */
export function generateCardGrid(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateSummary(data.basics.summary),
    generateTwoColumnCards(data),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with card styling
 */
function generatePreamble(): string {
  return `// Card Grid Resume — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 1.5cm, right: 1.5cm, top: 1.5cm, bottom: 1.5cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 10pt,
  fill: rgb("#1f2937"),
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette (Modern vibrant purple) —
#let card-accent = rgb("#8b5cf6")
#let card-border = rgb("#a78bfa")
#let card-bg     = rgb("#faf5ff")
#let header-color = rgb("#6d28d9")
#let text-primary = rgb("#1f2937")
#let text-secondary = rgb("#6b7280")

// — Card component —
#let card(title, body) = {
  block(
    width: 100%,
    inset: 10pt,
    radius: 4pt,
    fill: card-bg,
    stroke: (left: 3pt + card-accent, top: 0.5pt + card-border, right: 0.5pt + card-border, bottom: 0.5pt + card-border),
  )[
    #text(size: 12pt, weight: "bold", fill: card-accent, title)
    #v(0.3em)
    #body
  ]
  v(0.5em)
}

// — Reusable components —
#let cv-section(title) = {
  v(0.5em)
  text(size: 16pt, weight: "bold", fill: header-color, title)
  v(0.4em)
}

#let card-event(title, subtitle, date, location) = {
  text(weight: "bold", fill: text-primary, title)
  linebreak()
  text(style: "italic", fill: card-accent, subtitle)
  linebreak()
  text(size: 9pt, fill: text-secondary)[#date • #location]
  v(0.3em)
}

#let card-skill(keyword) = {
  box(
    inset: (x: 4pt, y: 2pt),
    radius: 3pt,
    fill: card-accent.lighten(80%),
    text(size: 9pt, weight: "bold", fill: card-accent, keyword),
  )
  h(2pt)
}`;
}

/**
 * Generate header
 */
function generateHeader(basics: ResumeData['basics']): string {
  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(
      `✉ #link("mailto:${basics.email}")[${escapeTypst(basics.email)}]`
    );
  }
  if (basics.phone) {
    contactParts.push(`☎ ${escapeTypst(basics.phone)}`);
  }
  if (basics.location) {
    contactParts.push(`📍 ${escapeTypst(basics.location)}`);
  }

  basics.profiles.forEach((profile) => {
    const icon = networkToIcon(profile.network);
    const label = cleanURL(profile.url);
    contactParts.push(
      `${icon} #link("${profile.url}")[${escapeTypst(label)}]`
    );
  });

  const contactLine = contactParts.join(' · ');

  return `// ── Header ──────────────────────────────────────────
#align(center)[
  #text(size: 24pt, weight: "bold", fill: header-color)[${escapeTypst(basics.name)}]
  #linebreak()
  #v(4pt)
  #text(size: 14pt, fill: card-accent)[${escapeTypst(basics.label)}]
  #v(8pt)
  #text(size: 9pt, fill: text-secondary)[${contactLine}]
]`;
}

/**
 * Generate summary section (full width)
 */
function generateSummary(summary?: string): string {
  if (!summary) return '';

  return `#cv-section("Professional Summary")
${escapeTypst(summary)}
#v(0.5em)`;
}

/**
 * Generate two-column card grid
 */
function generateTwoColumnCards(data: ResumeData): string {
  const leftCards = generateLeftCards(data);
  const rightCards = generateRightCards(data);

  return `// ── Two-column card grid ────────────────────────────
#grid(
  columns: (50%, 50%),
  column-gutter: 1em,
  // LEFT COLUMN
  [
${leftCards}
  ],
  // RIGHT COLUMN
  [
${rightCards}
  ],
)`;
}

/**
 * Generate left column cards (experience + education)
 */
function generateLeftCards(data: ResumeData): string {
  const cards: string[] = [];

  // Experience cards
  if (data.work && data.work.length > 0) {
    data.work.forEach((job) => {
      const dateRange = formatDateRange(job.startDate, job.endDate);

      let body = `#card-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

      if (job.highlights && job.highlights.length > 0) {
        const [description, ...bullets] = job.highlights;
        body += `\n${escapeTypst(description)}`;
        if (bullets.length > 0) {
          body += '\n' + bullets.map((b) => `- ${escapeTypst(b)}`).join('\n');
        }
      }

      cards.push(`    #card("Work Experience")[
      ${body}
    ]`);
    });
  }

  // Education card
  if (data.education && data.education.length > 0) {
    const eduEntries = data.education.map((edu) => {
      const degree = `${edu.studyType} of ${edu.area}`;
      const dateRange = formatDateRange(edu.startDate, edu.endDate);

      let entry = `*#text(fill: text-primary)[${escapeTypst(degree)}]*
      _#text(fill: card-accent)[${escapeTypst(edu.institution)}]_
      #text(size: 9pt, fill: text-secondary)[${dateRange} • ${escapeTypst(edu.location)}]`;

      if (edu.note) {
        entry += `\n      #text(size: 9pt)[${escapeTypst(edu.note)}]`;
      }

      return entry;
    });

    cards.push(`    #card("Education")[
      ${eduEntries.join('\n      #v(6pt)\n      ')}
    ]`);
  }

  return cards.join('\n\n');
}

/**
 * Generate right column cards (skills + projects + achievements + certifications)
 */
function generateRightCards(data: ResumeData): string {
  const cards: string[] = [];

  // Skills card
  if (data.skills && data.skills.length > 0) {
    const skillEntries = data.skills.map((skillGroup) => {
      const tags = skillGroup.keywords
        .map((k) => `#card-skill("${escapeTypst(k)}")`)
        .join('');
      return `*#text(fill: card-accent)[${escapeTypst(skillGroup.name)}]*
      ${tags}`;
    });

    cards.push(`    #card("Skills")[
      ${skillEntries.join('\n      #v(6pt)\n      ')}
    ]`);
  }

  // Project cards (top 3)
  if (data.projects && data.projects.length > 0) {
    data.projects.slice(0, 3).forEach((project) => {
      let body = `*#text(fill: text-primary)[${escapeTypst(project.name)}]*
      #text(size: 9pt, fill: text-secondary)[${escapeTypst(project.description)}]`;

      if (project.highlights && project.highlights.length > 0) {
        body += '\n' + project.highlights.map((h) => `      - ${escapeTypst(h)}`).join('\n');
      }

      cards.push(`    #card("Project")[
      ${body}
    ]`);
    });
  }

  // Achievements card
  if (data.achievements && data.achievements.length > 0) {
    const items = data.achievements
      .map((a) => `- ${escapeTypst(a)}`)
      .join('\n      ');

    cards.push(`    #card("Achievements")[
      ${items}
    ]`);
  }

  // Certifications card
  if (data.certifications && data.certifications.length > 0) {
    const items = data.certifications.slice(0, 6)
      .map((c) => `- ${escapeTypst(c)}`)
      .join('\n      ');

    cards.push(`    #card("Certifications")[
      ${items}
    ]`);
  }

  return cards.join('\n\n');
}
