/**
 * Banking & Finance Typst Generator
 * Conservative professional resume for finance and consulting
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
} from '@/lib/typst/utils';

/**
 * Generate complete Banking & Finance Typst code
 */
export function generateBankingResume(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateEducationSection(data.education),
    generateExperienceSection(data.work),
    generateSkillsSection(data.skills),
    generateAchievementsSection(data.achievements),
    generateCertificationsSection(data.certifications),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with conservative banking styling
 */
function generatePreamble(): string {
  return `// Banking & Finance Resume — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 2cm, right: 2cm, top: 2cm, bottom: 2cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 11pt,
  fill: black,
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Reusable components (conservative, no colors) —

#let cv-section(title) = {
  v(0.8em)
  text(size: 12pt, weight: "bold", upper(title))
  v(0.2em)
  line(length: 100%, stroke: 0.75pt + black)
  v(0.5em)
}

#let cv-event(position, company, date, location) = {
  v(0.3em)
  grid(
    columns: (1fr, auto),
    text(weight: "bold", company),
    text(size: 10pt, date),
  )
  grid(
    columns: (1fr, auto),
    text(style: "italic", position),
    text(size: 9pt, location),
  )
  v(0.4em)
}

#let cv-divider() = {
  v(0.5em)
}`;
}

/**
 * Generate header with personal information
 */
function generateHeader(basics: ResumeData['basics']): string {
  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(
      `#link("mailto:${basics.email}")[${escapeTypst(basics.email)}]`
    );
  }
  if (basics.phone) {
    contactParts.push(escapeTypst(basics.phone));
  }
  if (basics.location) {
    contactParts.push(escapeTypst(basics.location));
  }

  // LinkedIn only (most relevant for banking/finance)
  const linkedin = basics.profiles?.find((p) => p.network === 'LinkedIn');
  if (linkedin?.url) {
    contactParts.push(
      `#link("${linkedin.url}")[${escapeTypst(cleanURL(linkedin.url))}]`
    );
  }

  const contactLine = contactParts.join(' • ');

  let header = `// ── Header ──────────────────────────────────────────
#align(center)[
  #text(size: 20pt, weight: "bold")[${escapeTypst(basics.name)}]`;

  if (basics.label) {
    header += `
  #linebreak()
  #v(4pt)
  _${escapeTypst(basics.label)}_`;
  }

  header += `
  #linebreak()
  #v(4pt)
  #text(size: 9pt)[${contactLine}]
]`;

  return header;
}

/**
 * Generate education section (prioritized in banking resumes)
 */
function generateEducationSection(education?: ResumeData['education']): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu) => {
    const degree = `${edu.studyType} in ${edu.area}`;
    const dateRange = formatDateRange(edu.startDate, edu.endDate);

    let content = `#cv-event("${escapeTypst(degree)}", "${escapeTypst(edu.institution)}", "${dateRange}", "${escapeTypst(edu.location)}")`;

    const details: string[] = [];
    if (edu.gpa) {
      details.push(`GPA: ${escapeTypst(edu.gpa)}`);
    }
    if (edu.note) {
      details.push(escapeTypst(edu.note));
    }

    if (details.length > 0) {
      content += '\n' + details.join(' | ');
    }

    return content;
  });

  return `#cv-section("Education")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate experience section with focus on metrics
 */
function generateExperienceSection(work?: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const entries = work.map((job) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);

    let content = `#cv-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

    if (job.highlights && job.highlights.length > 0) {
      content += '\n' + job.highlights.map((h) => `- ${escapeTypst(h)}`).join('\n');
    }

    return content;
  });

  return `#cv-section("Professional Experience")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate skills section - simple list format
 */
function generateSkillsSection(skills?: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const groups = skills.map((skillGroup) => {
    const keywords = skillGroup.keywords.map((k) => escapeTypst(k)).join(', ');
    return `*${escapeTypst(skillGroup.name)}:* ${keywords}`;
  });

  return `#cv-section("Skills & Competencies")

${groups.join('\n\n')}`;
}

/**
 * Generate achievements section
 */
function generateAchievementsSection(achievements?: ResumeData['achievements']): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map((a) => `- ${escapeTypst(a)}`).join('\n');

  return `#cv-section("Awards & Honors")

${items}`;
}

/**
 * Generate certifications section
 */
function generateCertificationsSection(certifications?: ResumeData['certifications']): string {
  if (!certifications || certifications.length === 0) return '';

  const items = certifications.map((c) => `- ${escapeTypst(c)}`).join('\n');

  return `#cv-section("Certifications")

${items}`;
}
