/**
 * Typst Cover Letter Generator
 * Wraps a GPT-produced cover letter body in a formal business-letter layout
 * with sender header, date, and typographic defaults consistent with the resume.
 */

import type { ResumeData } from '@/lib/validation/schema';
import { escapeTypst } from './utils';

/**
 * Produce a complete Typst document for a cover letter.
 * The letter body is expected to already contain the salutation, paragraphs,
 * and closing (produced by the AI pipeline); this function wraps it with the
 * sender's contact header and the current date.
 * @param letterText - Cover letter body text from the AI pipeline
 * @param resume - Resume data, used for the sender's header
 * @returns Complete Typst document source
 */
export function generateCoverLetterTypst(
  letterText: string,
  resume: ResumeData
): string {
  const contactParts = [
    resume.basics.email,
    resume.basics.phone,
    resume.basics.location,
  ]
    .filter((part): part is string => Boolean(part && part.trim()))
    .map(escapeTypst);

  // Use middle-dot U+00B7 as a visual separator that renders well in Linux Libertine.
  const contact = contactParts.join(' · ');

  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const escapedBody = letterText
    .trim()
    .split(/\n\s*\n/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean)
    .map((paragraph) => escapeTypst(paragraph))
    .join('\n\n');

  return `// Cover Letter — Generated by Vitex
// Compile with: typst compile cover-letter.typ

#set page(
  paper: "a4",
  margin: (left: 2.5cm, right: 2.5cm, top: 2.5cm, bottom: 2.5cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 11pt,
  fill: rgb("#2E2E2E"),
  lang: "en",
)

#set par(
  leading: 0.75em,
  justify: true,
  first-line-indent: 0em,
)

#let primary = rgb("#0E5484")
#let accent  = rgb("#2E86AB")
#let muted   = rgb("#666666")

// ── Sender header ───────────────────────────────────
#text(size: 18pt, weight: "bold", fill: rgb("#2E2E2E"))[${escapeTypst(resume.basics.name)}]

#v(0.3em)
#text(size: 9.5pt, fill: muted)[${contact}]

#v(0.7em)
#line(length: 100%, stroke: 1pt + accent)
#v(1.5em)

// ── Date ────────────────────────────────────────────
#text(fill: muted)[${escapeTypst(currentDate)}]

#v(1.5em)

// ── Letter body ─────────────────────────────────────
${escapedBody}
`;
}
