/**
 * Typst Resume Generator
 * Converts ResumeData to a professional two-column Typst resume document.
 * Replaces the LaTeX generator with native Typst markup.
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from './utils';

/**
 * Generate a complete Typst document from resume data.
 * Produces a two-column A4 resume with header, summary, experience,
 * projects, education, skills, achievements, certifications, and references.
 * @param data - Validated resume data object
 * @returns Complete Typst document source code
 */
export function generateTypstCode(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateBody(data),
  ];

  return sections.join('\n\n');
}

/**
 * Generate the Typst document preamble with page setup, colors, and styles.
 */
function generatePreamble(): string {
  return `// Resume — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 1.25cm, right: 1.25cm, top: 1.5cm, bottom: 1.5cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 10pt,
  fill: rgb("#2E2E2E"),
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette —
#let primary   = rgb("#0E5484")
#let accent    = rgb("#2E86AB")
#let textcolor = rgb("#2E2E2E")
#let lightgrey = rgb("#666666")

// — Reusable components —

/// Section heading with colored rule below.
#let cv-section(title) = {
  v(0.8em)
  text(
    size: 13pt,
    weight: "bold",
    fill: primary,
    upper(title),
  )
  v(0.2em)
  line(length: 100%, stroke: 1.5pt + accent)
  v(0.4em)
}

/// Event block for work / education entries.
#let cv-event(title, subtitle, date, location) = {
  v(0.3em)
  text(weight: "bold", fill: textcolor, title)
  linebreak()
  text(style: "italic", fill: primary, subtitle)
  linebreak()
  text(size: 9pt, fill: lightgrey, date + "  |  " + location)
  v(0.4em)
}

/// Colored tag box for skills.
#let cv-tag(keyword) = {
  box(
    inset: (x: 5pt, y: 3pt),
    radius: 3pt,
    fill: accent.lighten(80%),
    text(size: 9pt, weight: "bold", fill: textcolor, keyword),
  )
  h(3pt)
}

/// Thin accent-colored divider between entries.
#let cv-divider() = {
  v(0.4em)
  line(length: 100%, stroke: 0.5pt + accent.lighten(60%))
  v(0.4em)
}

/// Subsection heading for skill categories.
#let cv-subsection(title) = {
  v(0.6em)
  text(weight: "bold", fill: primary, upper(title))
  v(0.2em)
}`;
}

/**
 * Generate the header block with name, title, and contact information.
 */
function generateHeader(basics: ResumeData['basics']): string {
  const contactLines: string[] = [];

  if (basics.email) {
    contactLines.push(
      `#link("mailto:${basics.email}")[✉ ${escapeTypst(basics.email)}]`
    );
  }
  if (basics.phone) {
    contactLines.push(`☎ ${escapeTypst(basics.phone)}`);
  }
  if (basics.location) {
    contactLines.push(`📍 ${escapeTypst(basics.location)}`);
  }

  basics.profiles.forEach((profile) => {
    const icon = networkToIcon(profile.network);
    const label = profile.label || cleanURL(profile.url);
    contactLines.push(
      `#link("${profile.url}")[${icon} ${escapeTypst(label)}]`
    );
  });

  const contactBlock = contactLines
    .map((line) => `    ${line}`)
    .join(' \\\\\n');

  return `// ── Header ──────────────────────────────────────────
#grid(
  columns: (1fr, auto),
  align: (left, right),
  [
    #text(size: 24pt, weight: "bold", fill: textcolor)[${escapeTypst(basics.name)}]
    #linebreak()
    #text(size: 12pt, fill: primary)[${escapeTypst(basics.label)}]
  ],
  [
    #set text(size: 9pt, fill: lightgrey)
${contactBlock}
  ],
)

#v(0.8em)
#line(length: 100%, stroke: 2pt + accent)
#v(0.8em)`;
}

/**
 * Generate the two-column body of the resume.
 */
function generateBody(data: ResumeData): string {
  const leftColumn = [
    generateSummary(data.basics.summary),
    generateExperienceSection(data.work),
    generateProjectsSection(data.projects),
  ]
    .filter(Boolean)
    .join('\n\n');

  const rightColumn = [
    generateEducationSection(data.education),
    generateSkillsSection(data.skills),
    generateAchievementsSection(data.achievements),
    generateCertificationsSection(data.certifications),
    generateReferencesSection(data.references),
  ]
    .filter(Boolean)
    .join('\n\n');

  return `// ── Two-column layout ────────────────────────────────
#grid(
  columns: (60%, 40%),
  column-gutter: 1.5em,

  // LEFT COLUMN — Main content
  [
${indent(leftColumn, 4)}
  ],

  // RIGHT COLUMN — Sidebar
  [
${indent(rightColumn, 4)}
  ],
)`;
}

/**
 * Generate the summary / introduction section.
 */
function generateSummary(summary?: string): string {
  if (!summary) return '';

  return `#cv-section("Introduction")
${escapeTypst(summary)}`;
}

/**
 * Generate the work experience section.
 */
function generateExperienceSection(work: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const entries = work.map((job, index) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);
    const subtitle = `${escapeTypst(job.company)} — ${escapeTypst(job.type)}`;

    let content = `#cv-event("${escapeTypst(job.position)}", "${subtitle}", "${dateRange}", "${escapeTypst(job.location)}")`;

    if (job.highlights && job.highlights.length > 0) {
      const [description, ...bullets] = job.highlights;
      content += `\n${escapeTypst(description)}`;

      if (bullets.length > 0) {
        content +=
          '\n\n' +
          bullets.map((b) => `- ${escapeTypst(b)}`).join('\n');
      }
    }

    if (index < work.length - 1) {
      content += '\n\n#cv-divider()';
    }

    return content;
  });

  return `#cv-section("Experience")

${entries.join('\n\n')}`;
}

/**
 * Generate the projects section in a 2-column sub-grid.
 */
function generateProjectsSection(projects: ResumeData['projects']): string {
  if (!projects || projects.length === 0) return '';

  const cells = projects.map((project) => {
    let cell = `[
  *${escapeTypst(project.name)}* — ${escapeTypst(project.description)}`;

    if (project.highlights && project.highlights.length > 0) {
      cell +=
        '\n\n  ' +
        project.highlights.map((h) => escapeTypst(h)).join(' ');
    }

    cell += '\n]';
    return cell;
  });

  // Pair cells into rows for a 2-column grid
  const gridCells = cells.join(',\n  ');

  return `#cv-section("Recent Projects / Open-Source")

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1em,
  row-gutter: 1em,
  ${gridCells},
)`;
}

/**
 * Generate the education section.
 */
function generateEducationSection(
  education: ResumeData['education']
): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu, index) => {
    const dateRange = formatDateRange(edu.startDate, edu.endDate);
    const degree = `${edu.studyType} of ${edu.area}`;

    let content = `#cv-event("${escapeTypst(degree)}", "${escapeTypst(edu.institution)}", "${dateRange}", "${escapeTypst(edu.location)}")`;

    if (edu.gpa) {
      content += `\nGPA: ${escapeTypst(edu.gpa)}`;
    }
    if (edu.note) {
      content += `\n#text(size: 9pt)[${escapeTypst(edu.note)}]`;
    }

    if (index < education.length - 1) {
      content += '\n\n#cv-divider()';
    }

    return content;
  });

  return `#cv-section("Education")

${entries.join('\n\n')}`;
}

/**
 * Generate the skills section with colored tag boxes.
 */
function generateSkillsSection(skills: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const categories = skills.map((skill) => {
    const tags = skill.keywords
      .map((kw) => `#cv-tag("${escapeTypst(kw)}")`)
      .join('\n');
    return `#cv-subsection("${escapeTypst(skill.name)}")
${tags}`;
  });

  return `#cv-section("Skills")

${categories.join('\n\n')}`;
}

/**
 * Generate the achievements section.
 */
function generateAchievementsSection(achievements: string[]): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map((a) => `- ${escapeTypst(a)}`).join('\n');

  return `#cv-section("Achievements & Communities")

${items}`;
}

/**
 * Generate the certifications section grouped by category.
 */
function generateCertificationsSection(certifications: string[]): string {
  if (!certifications || certifications.length === 0) return '';

  const groups = categorizeCertifications(certifications);
  const sections: string[] = [];

  const groupDefs: { key: keyof typeof groups; label: string }[] = [
    { key: 'coreDev', label: 'Core Development' },
    { key: 'frameworks', label: 'Frameworks & Languages' },
    { key: 'database', label: 'Database & API' },
    { key: 'tools', label: 'Development Tools & Practices' },
    { key: 'other', label: 'Other' },
  ];

  for (const { key, label } of groupDefs) {
    const certs = groups[key];
    if (certs.length > 0) {
      const items = certs.map((c) => `- ${escapeTypst(c)}`).join('\n');
      if (key === 'other') {
        sections.push(items);
      } else {
        sections.push(`#cv-subsection("${label}")\n${items}`);
      }
    }
  }

  return `#cv-section("Certifications")

${sections.join('\n\n')}`;
}

/**
 * Generate the references section.
 */
function generateReferencesSection(references?: string): string {
  if (!references) return '';

  return `#cv-section("References")

${escapeTypst(references)}`;
}

// ── Helpers ──────────────────────────────────────────────

/**
 * Indent every line of text by a given number of spaces.
 */
function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : pad + line))
    .join('\n');
}

/**
 * Categorize certifications by keyword matching.
 */
function categorizeCertifications(certifications: string[]) {
  const groups = {
    coreDev: [] as string[],
    frameworks: [] as string[],
    database: [] as string[],
    tools: [] as string[],
    other: [] as string[],
  };

  for (const cert of certifications) {
    const lower = cert.toLowerCase();
    if (
      lower.includes('frontend') ||
      lower.includes('software engineer') ||
      lower.includes('problem solving')
    ) {
      groups.coreDev.push(cert);
    } else if (
      lower.includes('react') ||
      lower.includes('angular') ||
      lower.includes('node') ||
      lower.includes('javascript') ||
      lower.includes('java') ||
      lower.includes('go')
    ) {
      groups.frameworks.push(cert);
    } else if (
      lower.includes('sql') ||
      lower.includes('data') ||
      lower.includes('rest api')
    ) {
      groups.database.push(cert);
    } else if (
      lower.includes('github') ||
      lower.includes('docker') ||
      lower.includes('ubuntu') ||
      lower.includes('agile') ||
      lower.includes('system') ||
      lower.includes('project') ||
      lower.includes('cyber')
    ) {
      groups.tools.push(cert);
    } else {
      groups.other.push(cert);
    }
  }

  return groups;
}
