/**
 * Academic Research Typst Generator
 * Comprehensive CV for researchers and academics with page numbering
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from '@/lib/typst/utils';

/**
 * Generate complete Academic Research Typst code
 */
export function generateAcademicCV(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateResearchInterests(data.basics.summary),
    generateEducationSection(data.education),
    generateResearchExperienceSection(data.work),
    generatePublicationsSection(data.projects),
    generateAchievementsSection(data.achievements),
    generateSkillsSection(data.skills),
    generateCertificationsSection(data.certifications),
    generateReferencesSection(data.references),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with academic styling
 */
function generatePreamble(): string {
  return `// Academic Research CV — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 2.5cm, right: 2.5cm, top: 2.5cm, bottom: 2.5cm),
  numbering: "1",
)

#set text(
  font: "Linux Libertine",
  size: 11pt,
  fill: black,
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette (academic: understated blue links) —
#let link-color = rgb("#00338a")

// — Reusable components —

#let cv-section(title) = {
  v(1em)
  text(size: 12pt, weight: "bold", upper(title))
  v(0.2em)
  line(length: 100%, stroke: 0.75pt + black)
  v(0.6em)
}

#let cv-event(title, subtitle, date, location) = {
  v(0.3em)
  grid(
    columns: (1fr, auto),
    [*#title*, _#subtitle _],
    text(size: 10pt, date),
  )
  text(size: 10pt, location)
  v(0.4em)
}

#let cv-divider() = {
  v(0.6em)
}`;
}

/**
 * Generate header with personal information
 */
function generateHeader(basics: ResumeData['basics']): string {
  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(
      `✉ #link("mailto:${basics.email}")[${escapeTypst(basics.email)}]`
    );
  }
  if (basics.phone) {
    contactParts.push(`☎ ${escapeTypst(basics.phone)}`);
  }
  if (basics.location) {
    contactParts.push(`📍 ${escapeTypst(basics.location)}`);
  }

  basics.profiles?.forEach((profile) => {
    if (profile.network && profile.url) {
      const icon = networkToIcon(profile.network);
      const label = cleanURL(profile.url);
      contactParts.push(
        `${icon} #link("${profile.url}")[${escapeTypst(label)}]`
      );
    }
  });

  const contactLine = contactParts.join(' • ');

  let header = `// ── Header ──────────────────────────────────────────
#align(center)[
  #text(size: 20pt, smallcaps[*${escapeTypst(basics.name)}*])`;

  if (basics.label) {
    header += `
  #linebreak()
  #v(4pt)
  _${escapeTypst(basics.label)}_`;
  }

  header += `
  #linebreak()
  #v(4pt)
  #text(size: 9pt)[${contactLine}]
]`;

  return header;
}

/**
 * Generate research interests section
 */
function generateResearchInterests(summary?: string): string {
  if (!summary) return '';

  return `#cv-section("Research Interests")
${escapeTypst(summary)}`;
}

/**
 * Generate education section with academic details
 */
function generateEducationSection(education?: ResumeData['education']): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu) => {
    const degree = `${edu.studyType} in ${edu.area}`;
    const dateRange = formatDateRange(edu.startDate, edu.endDate);

    let content = `#cv-event("${escapeTypst(degree)}", "${escapeTypst(edu.institution)}", "${dateRange}", "${escapeTypst(edu.location)}")`;

    const details: string[] = [];
    if (edu.gpa) {
      details.push(`GPA: ${escapeTypst(edu.gpa)}`);
    }
    if (edu.note) {
      details.push(escapeTypst(edu.note));
    }

    if (details.length > 0) {
      content += '\n' + details.join(' | ');
    }

    return content;
  });

  return `#cv-section("Education")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate research experience section
 */
function generateResearchExperienceSection(work?: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const entries = work.map((job) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);

    let content = `#cv-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

    if (job.highlights && job.highlights.length > 0) {
      content += '\n' + job.highlights.map((h) => `- ${escapeTypst(h)}`).join('\n');
    }

    return content;
  });

  return `#cv-section("Research Experience")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate publications section (uses projects data, numbered list)
 */
function generatePublicationsSection(projects?: ResumeData['projects']): string {
  if (!projects || projects.length === 0) return '';

  const entries = projects.map((project, index) => {
    let entry = `${index + 1}. *${escapeTypst(project.name)}*`;

    if (project.description) {
      entry += `\n\n${escapeTypst(project.description)}`;
    }

    if (project.url) {
      entry += `\n\n#link("${project.url}")[${escapeTypst(cleanURL(project.url))}]`;
    }

    if (project.highlights && project.highlights.length > 0) {
      entry += '\n\n' + project.highlights.map((h) => `  - ${escapeTypst(h)}`).join('\n');
    }

    return entry;
  });

  return `#cv-section("Publications & Research Projects")

${entries.join('\n\n')}`;
}

/**
 * Generate achievements section
 */
function generateAchievementsSection(achievements?: ResumeData['achievements']): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map((a) => `- ${escapeTypst(a)}`).join('\n');

  return `#cv-section("Awards & Honors")

${items}`;
}

/**
 * Generate skills section
 */
function generateSkillsSection(skills?: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const groups = skills.map((skillGroup) => {
    const keywords = skillGroup.keywords.map((k) => escapeTypst(k)).join(', ');
    return `*${escapeTypst(skillGroup.name)}:* ${keywords}`;
  });

  return `#cv-section("Technical Skills")

${groups.join('\n\n')}`;
}

/**
 * Generate certifications section
 */
function generateCertificationsSection(certifications?: ResumeData['certifications']): string {
  if (!certifications || certifications.length === 0) return '';

  const items = certifications.map((c) => `- ${escapeTypst(c)}`).join('\n');

  return `#cv-section("Certifications & Professional Development")

${items}`;
}

/**
 * Generate references section
 */
function generateReferencesSection(references?: ResumeData['references']): string {
  if (!references) return '';

  return `#cv-section("References")

${escapeTypst(references)}`;
}
