/**
 * Executive Resume Typst Generator
 * Professional executive resume for C-level and senior management
 * Deep blue and gold color scheme
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from '@/lib/typst/utils';

/**
 * Generate complete Executive Resume Typst code
 */
export function generateExecutiveResume(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateExecutiveSummary(data.basics.summary),
    generateExperienceSection(data.work),
    generateEducationSection(data.education),
    generateLeadershipSection(data.achievements),
    generateSkillsSection(data.skills),
    generateCertificationsSection(data.certifications),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with executive styling
 */
function generatePreamble(): string {
  return `// Executive Resume — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 2.5cm, right: 2.5cm, top: 2cm, bottom: 2cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 11pt,
  fill: rgb("#1f2937"),
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette (Executive: deep blue + gold) —
#let primary   = rgb("#1e3a8a")
#let accent    = rgb("#d97706")
#let secondary = rgb("#475569")
#let gold      = rgb("#eab308")

// — Reusable components —

#let cv-section(title) = {
  v(0.8em)
  text(size: 16pt, weight: "bold", fill: primary, upper(title))
  v(0.2em)
  line(length: 100%, stroke: 1.5pt + accent)
  v(0.1em)
  line(length: 100%, stroke: 0.75pt + accent)
  v(0.5em)
}

#let cv-event(title, subtitle, date, location) = {
  v(0.3em)
  grid(
    columns: (1fr, auto),
    text(size: 12pt, weight: "bold", fill: primary, title),
    text(size: 10pt, weight: "bold", fill: secondary, date),
  )
  grid(
    columns: (1fr, auto),
    text(style: "italic", fill: accent, subtitle),
    text(size: 9pt, fill: secondary, location),
  )
  v(0.4em)
}

#let cv-tag(keyword) = {
  box(
    inset: (x: 5pt, y: 3pt),
    radius: 3pt,
    fill: primary.lighten(85%),
    text(size: 9pt, weight: "bold", fill: primary, keyword),
  )
  h(3pt)
}

#let cv-divider() = {
  v(0.6em)
}`;
}

/**
 * Generate header with personal information
 */
function generateHeader(basics: ResumeData['basics']): string {
  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(
      `#link("mailto:${basics.email}")[✉ ${escapeTypst(basics.email)}]`
    );
  }
  if (basics.phone) {
    contactParts.push(`☎ ${escapeTypst(basics.phone)}`);
  }
  if (basics.location) {
    contactParts.push(`📍 ${escapeTypst(basics.location)}`);
  }

  basics.profiles?.forEach((profile) => {
    if (profile.network && profile.url) {
      const icon = networkToIcon(profile.network);
      const label = cleanURL(profile.url);
      contactParts.push(
        `#link("${profile.url}")[${icon} ${escapeTypst(label)}]`
      );
    }
  });

  const contactLine = contactParts.join(' #text(fill: secondary)[ | ] ');

  return `// ── Header ──────────────────────────────────────────
#align(center)[
  #text(size: 28pt, weight: "bold", fill: primary)[${escapeTypst(basics.name)}]
  #linebreak()
  #v(4pt)
  #text(size: 16pt, fill: secondary)[${escapeTypst(basics.label)}]
  #v(4pt)
  #text(size: 9pt, fill: secondary)[${contactLine}]
]`;
}

/**
 * Generate executive summary section
 */
function generateExecutiveSummary(summary?: string): string {
  if (!summary) return '';

  return `#cv-section("Executive Summary")
${escapeTypst(summary)}`;
}

/**
 * Generate experience section with emphasis on leadership
 */
function generateExperienceSection(work?: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const entries = work.map((job) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);

    let content = `#cv-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

    if (job.highlights && job.highlights.length > 0) {
      content += '\n' + job.highlights.map((h) => `- ${escapeTypst(h)}`).join('\n');
    }

    return content;
  });

  return `#cv-section("Professional Experience")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate education section
 */
function generateEducationSection(education?: ResumeData['education']): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu) => {
    const degree = `${edu.studyType} in ${edu.area}`;
    const dateRange = formatDateRange(edu.startDate, edu.endDate);

    let content = `#cv-event("${escapeTypst(degree)}", "${escapeTypst(edu.institution)}", "${dateRange}", "${escapeTypst(edu.location)}")`;

    const details: string[] = [];
    if (edu.gpa) {
      details.push(`GPA: ${escapeTypst(edu.gpa)}`);
    }
    if (edu.note) {
      details.push(escapeTypst(edu.note));
    }

    if (details.length > 0) {
      content += '\n' + details.join(' | ');
    }

    return content;
  });

  return `#cv-section("Education")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate leadership & achievements section
 */
function generateLeadershipSection(achievements?: ResumeData['achievements']): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map((a) => `- ${escapeTypst(a)}`).join('\n');

  return `#cv-section("Leadership & Achievements")

${items}`;
}

/**
 * Generate skills section with tags
 */
function generateSkillsSection(skills?: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const groups = skills.map((skillGroup) => {
    const tags = skillGroup.keywords
      .map((kw) => `#cv-tag("${escapeTypst(kw)}")`)
      .join(' ');
    return `*#text(fill: secondary)[${escapeTypst(skillGroup.name)}:]*
${tags}`;
  });

  return `#cv-section("Core Competencies")

${groups.join('\n\n')}`;
}

/**
 * Generate certifications section
 */
function generateCertificationsSection(certifications?: ResumeData['certifications']): string {
  if (!certifications || certifications.length === 0) return '';

  const items = certifications.map((c) => `- ${escapeTypst(c)}`).join('\n');

  return `#cv-section("Professional Certifications")

${items}`;
}
