/**
 * Compact One-Page Typst Generator
 * Space-efficient resume with minimal margins for dense content
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from '@/lib/typst/utils';

/**
 * Generate complete Compact One-Page Typst code
 */
export function generateCompactResume(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateSummary(data.basics.summary),
    generateEducationSection(data.education),
    generateExperienceSection(data.work),
    generateProjectsSection(data.projects),
    generateSkillsSection(data.skills),
    generateAchievementsSection(data.achievements),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with compact styling
 */
function generatePreamble(): string {
  return `// Compact One-Page Resume — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 1cm, right: 1cm, top: 1cm, bottom: 1cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 9pt,
  fill: rgb("#0f172a"),
  lang: "en",
)

#set par(
  leading: 0.55em,
  justify: false,
)

// — Color palette —
#let primary   = rgb("#0f172a")
#let accent    = rgb("#0284c7")
#let secondary = rgb("#64748b")

// — Reusable components —

#let cv-section(title) = {
  v(0.4em)
  text(size: 11pt, weight: "bold", fill: primary, upper(title))
  v(0.1em)
  line(length: 100%, stroke: 1pt + accent)
  v(0.3em)
}

#let cv-event(title, subtitle, date, location) = {
  v(0.15em)
  grid(
    columns: (1fr, auto),
    [*#title* | _#subtitle _],
    text(size: 8pt, fill: secondary, date),
  )
  text(size: 8pt, fill: secondary, location)
  v(0.2em)
}

#let cv-tag(keyword) = {
  box(
    inset: (x: 3pt, y: 2pt),
    radius: 2pt,
    fill: accent.lighten(85%),
    text(size: 8pt, weight: "bold", fill: accent, keyword),
  )
  h(2pt)
}

#let cv-divider() = {
  v(0.2em)
}`;
}

/**
 * Generate compact header with personal information
 */
function generateHeader(basics: ResumeData['basics']): string {
  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(
      `#link("mailto:${basics.email}")[✉ ${escapeTypst(basics.email)}]`
    );
  }
  if (basics.phone) {
    contactParts.push(`☎ ${escapeTypst(basics.phone)}`);
  }
  if (basics.location) {
    contactParts.push(`📍 ${escapeTypst(basics.location)}`);
  }

  basics.profiles?.forEach((profile) => {
    if (profile.network && profile.url) {
      const icon = networkToIcon(profile.network);
      const label = cleanURL(profile.url);
      contactParts.push(
        `#link("${profile.url}")[${icon} ${escapeTypst(label)}]`
      );
    }
  });

  const contactLine = contactParts.join(' | ');

  let header = `// ── Header ──────────────────────────────────────────
#align(center)[
  #text(size: 18pt, weight: "bold", fill: primary)[${escapeTypst(basics.name)}]`;

  if (basics.label) {
    header += `
  #linebreak()
  #text(size: 9pt, style: "italic", fill: secondary)[${escapeTypst(basics.label)}]`;
  }

  header += `
  #linebreak()
  #text(size: 8pt, fill: secondary)[${contactLine}]
]`;

  return header;
}

/**
 * Generate summary section
 */
function generateSummary(summary?: string): string {
  if (!summary) return '';

  return `#cv-section("Summary")
#text(size: 9pt)[${escapeTypst(summary)}]`;
}

/**
 * Generate education section
 */
function generateEducationSection(education?: ResumeData['education']): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu) => {
    const degree = `${edu.studyType} in ${edu.area}`;
    const dateRange = formatDateRange(edu.startDate, edu.endDate);

    let content = `#cv-event("${escapeTypst(degree)}", "${escapeTypst(edu.institution)}", "${dateRange}", "${escapeTypst(edu.location)}")`;

    const details: string[] = [];
    if (edu.gpa) {
      details.push(`GPA: ${escapeTypst(edu.gpa)}`);
    }
    if (edu.note) {
      details.push(escapeTypst(edu.note));
    }

    if (details.length > 0) {
      content += `\n#text(size: 8pt)[${details.join(' | ')}]`;
    }

    return content;
  });

  return `#cv-section("Education")

${entries.join('\n\n')}`;
}

/**
 * Generate experience section
 */
function generateExperienceSection(work?: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const entries = work.map((job) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);

    let content = `#cv-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

    if (job.highlights && job.highlights.length > 0) {
      // Limit to top 3 highlights for compact layout
      const topHighlights = job.highlights.slice(0, 3);
      content += '\n#text(size: 8pt)[\n' + topHighlights.map((h) => `  - ${escapeTypst(h)}`).join('\n') + '\n]';
    }

    return content;
  });

  return `#cv-section("Experience")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate projects section
 */
function generateProjectsSection(projects?: ResumeData['projects']): string {
  if (!projects || projects.length === 0) return '';

  const entries = projects.map((project) => {
    let header = `*${escapeTypst(project.name)}*`;
    if (project.url) {
      header = `#link("${project.url}")[*${escapeTypst(project.name)}*]`;
    }

    let content = header;

    if (project.description) {
      content += `\n#text(size: 8pt)[${escapeTypst(project.description)}]`;
    }

    if (project.highlights && project.highlights.length > 0) {
      const topHighlights = project.highlights.slice(0, 2);
      content += '\n#text(size: 8pt)[\n' + topHighlights.map((h) => `  - ${escapeTypst(h)}`).join('\n') + '\n]';
    }

    return content;
  });

  return `#cv-section("Projects")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate skills section with compact tag cloud
 */
function generateSkillsSection(skills?: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const groups = skills.map((skillGroup) => {
    const tags = skillGroup.keywords
      .map((kw) => `#cv-tag("${escapeTypst(kw)}")`)
      .join(' ');
    return `*#text(size: 8pt)[${escapeTypst(skillGroup.name)}:]* ${tags}`;
  });

  return `#cv-section("Skills")

${groups.join('\n\n')}`;
}

/**
 * Generate achievements section
 */
function generateAchievementsSection(achievements?: ResumeData['achievements']): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map((a) => `- #text(size: 8pt)[${escapeTypst(a)}]`).join('\n');

  return `#cv-section("Achievements")

${items}`;
}
