/**
 * Three-Section Column Typst Generator
 * Hybrid layout: full-width banner header + 30/70 columns + full-width footer
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from '@/lib/typst/utils';

/**
 * Generate complete Three-Section Column Typst code
 */
export function generateThreeSection(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateBannerHeader(data.basics),
    generateTwoColumnBody(data),
    generateFooter(data),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with three-section styling
 */
function generatePreamble(): string {
  return `// Three-Section Resume — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 1.25cm, right: 1.25cm, top: 4.5cm, bottom: 1.5cm),
  numbering: none,
  background: place(top, rect(width: 100%, height: 3.5cm, fill: gradient.linear(rgb("#1e40af"), rgb("#3b82f6"), angle: 0deg))),
)

#set text(
  font: "Linux Libertine",
  size: 10pt,
  fill: rgb("#1f2937"),
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette (Gradient blue) —
#let banner-start = rgb("#1e40af")
#let banner-end   = rgb("#3b82f6")
#let accent       = rgb("#60a5fa")
#let sidebar-bg   = rgb("#eff6ff")
#let text-primary = rgb("#1f2937")
#let text-secondary = rgb("#6b7280")

// — Reusable components —

#let cv-section(title) = {
  v(0.8em)
  text(size: 13pt, weight: "bold", fill: banner-start, upper(title))
  v(0.2em)
  line(length: 100%, stroke: 1.5pt + accent)
  v(0.4em)
}

#let sidebar-section(title) = {
  v(0.6em)
  text(size: 11pt, weight: "bold", fill: banner-start, upper(title))
  v(0.3em)
}

#let cv-event(title, subtitle, date, location) = {
  v(0.3em)
  grid(
    columns: (1fr, auto),
    text(size: 11pt, weight: "bold", fill: text-primary, title),
    text(size: 9pt, style: "italic", fill: text-secondary, date),
  )
  grid(
    columns: (1fr, auto),
    text(style: "italic", fill: accent, subtitle),
    text(size: 9pt, fill: text-secondary, location),
  )
  v(0.4em)
}

#let skill-badge(keyword) = {
  box(
    inset: (x: 4pt, y: 2pt),
    radius: 3pt,
    fill: accent.lighten(80%),
    text(size: 9pt, weight: "bold", fill: banner-start, keyword),
  )
  h(2pt)
}

#let cv-divider() = {
  v(0.4em)
  line(length: 100%, stroke: 0.5pt + accent.lighten(70%))
  v(0.4em)
}`;
}

/**
 * Generate banner header (Section 1)
 */
function generateBannerHeader(basics: ResumeData['basics']): string {
  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(`✉ ${escapeTypst(basics.email)}`);
  }
  if (basics.phone) {
    contactParts.push(`☎ ${escapeTypst(basics.phone)}`);
  }
  if (basics.location) {
    contactParts.push(`📍 ${escapeTypst(basics.location)}`);
  }

  basics.profiles.forEach((profile) => {
    const icon = networkToIcon(profile.network);
    const label = cleanURL(profile.url);
    contactParts.push(`${icon} ${escapeTypst(label)}`);
  });

  const contactLine = contactParts.join(' • ');

  return `// ── Section 1: Banner Header ────────────────────────
#place(top + center, dy: -3.5cm)[
  #text(size: 28pt, weight: "bold", fill: white)[${escapeTypst(basics.name)}]
  #linebreak()
  #v(6pt)
  #text(size: 14pt, fill: white.darken(10%))[${escapeTypst(basics.label)}]
  #v(8pt)
  #text(size: 9pt, fill: white.darken(5%))[${contactLine}]
]`;
}

/**
 * Generate two-column body (Section 2)
 */
function generateTwoColumnBody(data: ResumeData): string {
  const leftSidebar = generateLeftSidebar(data);
  const rightMain = generateRightMain(data);

  return `// ── Section 2: Two-column body ──────────────────────
#grid(
  columns: (30%, 70%),
  column-gutter: 1.2em,
  // Left sidebar (30%)
  rect(
    width: 100%,
    fill: sidebar-bg,
    inset: 0.5cm,
    radius: 4pt,
  )[
${leftSidebar}
  ],
  // Right main content (70%)
  [
${rightMain}
  ],
)`;
}

/**
 * Generate left sidebar content
 */
function generateLeftSidebar(data: ResumeData): string {
  const parts: string[] = [];

  // Skills
  if (data.skills && data.skills.length > 0) {
    const skillLines: string[] = [];
    data.skills.forEach((skillGroup) => {
      skillLines.push(`    *#text(fill: banner-start)[${escapeTypst(skillGroup.name)}]*`);
      const badges = skillGroup.keywords
        .map((k) => `#skill-badge("${escapeTypst(k)}")`)
        .join('');
      skillLines.push(`    ${badges}`);
      skillLines.push('    #v(6pt)');
    });

    parts.push(`    #sidebar-section("Skills")
${skillLines.join('\n')}`);
  }

  // Education
  if (data.education && data.education.length > 0) {
    const eduLines: string[] = [];
    data.education.forEach((edu) => {
      const degree = `${edu.studyType} of ${edu.area}`;
      const dateRange = formatDateRange(edu.startDate, edu.endDate);
      eduLines.push(`    *#text(fill: text-primary)[${escapeTypst(degree)}]*
    #text(size: 9pt, style: "italic")[${escapeTypst(edu.institution)}]
    #text(size: 9pt, fill: text-secondary)[${dateRange}]`);

      if (edu.note) {
        eduLines.push(`    #text(size: 9pt)[${escapeTypst(edu.note)}]`);
      }
      eduLines.push('    #v(6pt)');
    });

    parts.push(`    #sidebar-section("Education")
${eduLines.join('\n')}`);
  }

  // Certifications (top 5)
  if (data.certifications && data.certifications.length > 0) {
    const items = data.certifications.slice(0, 5)
      .map((c) => `    • #text(size: 9pt)[${escapeTypst(c)}]`)
      .join(' \\\\\n');
    parts.push(`    #sidebar-section("Certifications")
${items}`);
  }

  return parts.join('\n\n');
}

/**
 * Generate right main content
 */
function generateRightMain(data: ResumeData): string {
  const sections: string[] = [];

  // Summary
  if (data.basics.summary) {
    sections.push(`    #cv-section("Professional Summary")
    ${escapeTypst(data.basics.summary)}`);
  }

  // Experience
  if (data.work && data.work.length > 0) {
    const entries = data.work.map((job, index) => {
      const dateRange = formatDateRange(job.startDate, job.endDate);

      let content = `    #cv-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

      if (job.highlights && job.highlights.length > 0) {
        const [description, ...bullets] = job.highlights;
        content += `\n    ${escapeTypst(description)}`;
        if (bullets.length > 0) {
          content += '\n' + bullets.map((b) => `    - ${escapeTypst(b)}`).join('\n');
        }
      }

      if (index < data.work.length - 1) {
        content += '\n    #cv-divider()';
      }

      return content;
    });

    sections.push(`    #cv-section("Work Experience")

${entries.join('\n\n')}`);
  }

  // Projects
  if (data.projects && data.projects.length > 0) {
    const entries = data.projects.map((project, index) => {
      let content = `    *#text(size: 11pt, fill: text-primary)[${escapeTypst(project.name)}]* — ${escapeTypst(project.description)}`;

      if (project.highlights && project.highlights.length > 0) {
        content += '\n' + project.highlights.map((h) => `    - ${escapeTypst(h)}`).join('\n');
      }

      if (index < data.projects.length - 1) {
        content += '\n    #cv-divider()';
      }

      return content;
    });

    sections.push(`    #cv-section("Projects")

${entries.join('\n\n')}`);
  }

  return sections.join('\n\n');
}

/**
 * Generate footer (Section 3) - Achievements
 */
function generateFooter(data: ResumeData): string {
  if (!data.achievements || data.achievements.length === 0) return '';

  const items = data.achievements.map((a) => `- ${escapeTypst(a)}`).join('\n');

  return `// ── Section 3: Full-width footer ────────────────────
#v(0.5em)
#line(length: 100%, stroke: 1pt + accent)
#v(0.5em)

#cv-section("Achievements & Recognition")

${items}`;
}
