/**
 * Reverse Two-Column Typst Generator
 * 40/60 layout with skills sidebar on left, main content on right
 * Professional burgundy color scheme
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from '@/lib/typst/utils';

/**
 * Generate complete Reverse Two-Column Typst code
 */
export function generateReverseTwoColumn(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateTwoColumnBody(data),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with reverse column styling
 */
function generatePreamble(): string {
  return `// Reverse Two-Column Resume — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 1.25cm, right: 1.25cm, top: 1.5cm, bottom: 1.5cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 10pt,
  fill: rgb("#1f2937"),
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette (Burgundy) —
#let primary   = rgb("#7f1d1d")
#let accent    = rgb("#991b1b")
#let sidebar-bg = rgb("#f3f4f6")
#let text-primary = rgb("#1f2937")
#let text-secondary = rgb("#6b7280")

// — Reusable components —

#let cv-section(title) = {
  v(0.8em)
  text(size: 13pt, weight: "bold", fill: primary, upper(title))
  v(0.2em)
  line(length: 100%, stroke: 1.5pt + accent)
  v(0.4em)
}

#let sidebar-section(title) = {
  v(0.6em)
  text(size: 11pt, weight: "bold", fill: primary, upper(title))
  v(0.3em)
}

#let cv-event(title, subtitle, date, location) = {
  v(0.3em)
  grid(
    columns: (1fr, auto),
    text(size: 11pt, weight: "bold", fill: text-primary, title),
    text(size: 9pt, style: "italic", fill: text-secondary, date),
  )
  grid(
    columns: (1fr, auto),
    text(style: "italic", fill: primary, subtitle),
    text(size: 9pt, fill: text-secondary, location),
  )
  v(0.4em)
}

#let skill-tag(keyword) = {
  box(
    inset: (x: 4pt, y: 2pt),
    radius: 2pt,
    fill: accent.lighten(80%),
    text(size: 9pt, fill: primary, keyword),
  )
  h(2pt)
}

#let cv-divider() = {
  v(0.4em)
  line(length: 100%, stroke: 0.5pt + accent.lighten(70%))
  v(0.4em)
}`;
}

/**
 * Generate header with personal information
 */
function generateHeader(basics: ResumeData['basics']): string {
  return `// ── Header ──────────────────────────────────────────
#align(center)[
  #text(size: 24pt, weight: "bold", fill: primary)[${escapeTypst(basics.name)}]
  #linebreak()
  #v(4pt)
  #text(size: 12pt, fill: text-secondary)[${escapeTypst(basics.label)}]
]
#v(0.5em)
#line(length: 100%, stroke: 2pt + accent)
#v(0.5em)`;
}

/**
 * Generate two-column body: sidebar (40%) + main (60%)
 */
function generateTwoColumnBody(data: ResumeData): string {
  const leftSidebar = generateLeftSidebar(data);
  const rightMain = generateRightMain(data);

  return `// ── Two-column layout (40/60 reverse) ────────────────
#grid(
  columns: (40%, 60%),
  column-gutter: 1.5em,
  // LEFT SIDEBAR (40%)
  rect(
    width: 100%,
    fill: sidebar-bg,
    inset: 0.6cm,
    radius: 4pt,
  )[
${leftSidebar}
  ],
  // RIGHT MAIN (60%)
  [
${rightMain}
  ],
)`;
}

/**
 * Generate left sidebar content
 */
function generateLeftSidebar(data: ResumeData): string {
  const parts: string[] = [];

  // Contact
  const contactLines: string[] = [];
  if (data.basics.email) {
    contactLines.push(`    ✉ #link("mailto:${data.basics.email}")[#text(size: 9pt)[${escapeTypst(data.basics.email)}]]`);
  }
  if (data.basics.phone) {
    contactLines.push(`    ☎ #text(size: 9pt)[${escapeTypst(data.basics.phone)}]`);
  }
  if (data.basics.location) {
    contactLines.push(`    📍 #text(size: 9pt)[${escapeTypst(data.basics.location)}]`);
  }

  data.basics.profiles.forEach((profile) => {
    const icon = networkToIcon(profile.network);
    const label = cleanURL(profile.url);
    contactLines.push(`    ${icon} #link("${profile.url}")[#text(size: 9pt)[${escapeTypst(label)}]]`);
  });

  parts.push(`    #sidebar-section("Contact")
${contactLines.join(' \\\\\n')}`);

  // Skills
  if (data.skills && data.skills.length > 0) {
    const skillLines: string[] = [];
    data.skills.forEach((skillGroup) => {
      skillLines.push(`    *#text(fill: primary)[${escapeTypst(skillGroup.name)}]*`);
      const tags = skillGroup.keywords
        .map((k) => `#skill-tag("${escapeTypst(k)}")`)
        .join('');
      skillLines.push(`    ${tags}`);
      skillLines.push('    #v(6pt)');
    });

    parts.push(`    #sidebar-section("Skills")
${skillLines.join('\n')}`);
  }

  // Education
  if (data.education && data.education.length > 0) {
    const eduLines: string[] = [];
    data.education.forEach((edu) => {
      const degree = `${edu.studyType} of ${edu.area}`;
      const dateRange = formatDateRange(edu.startDate, edu.endDate);
      eduLines.push(`    *#text(fill: text-primary)[${escapeTypst(degree)}]*
    #text(size: 9pt, style: "italic")[${escapeTypst(edu.institution)}]
    #text(size: 9pt, fill: text-secondary)[${dateRange}]`);

      if (edu.note) {
        eduLines.push(`    #text(size: 9pt)[${escapeTypst(edu.note)}]`);
      }
      eduLines.push('    #v(6pt)');
    });

    parts.push(`    #sidebar-section("Education")
${eduLines.join('\n')}`);
  }

  // Achievements
  if (data.achievements && data.achievements.length > 0) {
    const items = data.achievements
      .map((a) => `    • #text(size: 9pt)[${escapeTypst(a)}]`)
      .join(' \\\\\n');
    parts.push(`    #sidebar-section("Achievements")
${items}`);
  }

  // Certifications
  if (data.certifications && data.certifications.length > 0) {
    const items = data.certifications
      .map((c) => `    • #text(size: 9pt)[${escapeTypst(c)}]`)
      .join(' \\\\\n');
    parts.push(`    #sidebar-section("Certifications")
${items}`);
  }

  return parts.join('\n\n');
}

/**
 * Generate right main content
 */
function generateRightMain(data: ResumeData): string {
  const sections: string[] = [];

  // Summary
  if (data.basics.summary) {
    sections.push(`    #cv-section("Professional Summary")
    ${escapeTypst(data.basics.summary)}`);
  }

  // Experience
  if (data.work && data.work.length > 0) {
    const entries = data.work.map((job, index) => {
      const dateRange = formatDateRange(job.startDate, job.endDate);

      let content = `    #cv-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

      if (job.highlights && job.highlights.length > 0) {
        const [description, ...bullets] = job.highlights;
        content += `\n    ${escapeTypst(description)}`;
        if (bullets.length > 0) {
          content += '\n' + bullets.map((b) => `    - ${escapeTypst(b)}`).join('\n');
        }
      }

      if (index < data.work.length - 1) {
        content += '\n    #cv-divider()';
      }

      return content;
    });

    sections.push(`    #cv-section("Work Experience")

${entries.join('\n\n')}`);
  }

  // Projects
  if (data.projects && data.projects.length > 0) {
    const entries = data.projects.map((project, index) => {
      let content = `    *#text(size: 11pt, fill: text-primary)[${escapeTypst(project.name)}]* — ${escapeTypst(project.description)}`;

      if (project.highlights && project.highlights.length > 0) {
        content += '\n' + project.highlights.map((h) => `    - ${escapeTypst(h)}`).join('\n');
      }

      if (index < data.projects.length - 1) {
        content += '\n    #cv-divider()';
      }

      return content;
    });

    sections.push(`    #cv-section("Projects")

${entries.join('\n\n')}`);
  }

  return sections.join('\n\n');
}
