/**
 * Classic Academic Typst Generator
 * Traditional academic CV style with education-first ordering
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
} from '@/lib/typst/utils';

/**
 * Generate complete Classic CV Typst code
 */
export function generateClassicCV(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateEducationSection(data.education),
    generateExperienceSection(data.work),
    generatePublicationsSection(data.projects),
    generateSkillsSection(data.skills),
    generateAchievementsSection(data.achievements),
    generateCertificationsSection(data.certifications),
    generateReferencesSection(data.references),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with classic academic styling
 */
function generatePreamble(): string {
  return `// Classic Academic CV — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 2.5cm, right: 2.5cm, top: 2.5cm, bottom: 2.5cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 11pt,
  fill: black,
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette —
#let link-color = rgb("#00338a")

// — Reusable components —

#let cv-section(title) = {
  v(1em)
  text(size: 12pt, weight: "bold", upper(title))
  v(0.2em)
  line(length: 100%, stroke: 0.75pt + black)
  v(0.6em)
}

#let cv-event(title, subtitle, date, location) = {
  v(0.3em)
  grid(
    columns: (1fr, auto),
    [*#title*, _#subtitle _],
    text(size: 10pt, date),
  )
  text(style: "italic", location)
  v(0.4em)
}

#let cv-divider() = {
  v(0.6em)
}`;
}

/**
 * Generate header with personal information
 */
function generateHeader(basics: ResumeData['basics']): string {
  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(`✉ ${escapeTypst(basics.email)}`);
  }
  if (basics.phone) {
    contactParts.push(`☎ ${escapeTypst(basics.phone)}`);
  }
  if (basics.location) {
    contactParts.push(`📍 ${escapeTypst(basics.location)}`);
  }

  basics.profiles?.forEach((profile) => {
    contactParts.push(escapeTypst(cleanURL(profile.url)));
  });

  const contactLine = contactParts.join('  |  ');

  let header = `// ── Header ──────────────────────────────────────────
#align(center)[
  #text(size: 20pt, smallcaps[*${escapeTypst(basics.name)}*])`;

  if (basics.label) {
    header += `
  #linebreak()
  #v(4pt)
  _${escapeTypst(basics.label)}_`;
  }

  header += `
  #v(8pt)
  #text(size: 9pt)[${contactLine}]
]`;

  if (basics.summary) {
    header += `

#v(12pt)
${escapeTypst(basics.summary)}`;
  }

  return header;
}

/**
 * Generate education section (first in classic academic CVs)
 */
function generateEducationSection(education: ResumeData['education']): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu) => {
    const degree = `${edu.studyType} in ${edu.area}`;
    const dateRange = formatDateRange(edu.startDate, edu.endDate);

    let content = `#cv-event("${escapeTypst(degree)}", "${escapeTypst(edu.institution)}", "${dateRange}", "${escapeTypst(edu.location)}")`;

    if (edu.gpa) {
      content += `\n_GPA: ${escapeTypst(edu.gpa)}_`;
    }
    if (edu.note) {
      content += `\n${escapeTypst(edu.note)}`;
    }

    content += '\n#cv-divider()';

    return content;
  });

  return `#cv-section("Education")

${entries.join('\n\n')}`;
}

/**
 * Generate work experience section
 */
function generateExperienceSection(work: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const entries = work.map((job) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);

    let content = `#cv-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

    if (job.highlights && job.highlights.length > 0) {
      content += '\n' + job.highlights.map((h) => `- ${escapeTypst(h)}`).join('\n');
    }

    content += '\n#cv-divider()';

    return content;
  });

  return `#cv-section("Professional Experience")

${entries.join('\n\n')}`;
}

/**
 * Generate publications/projects section (numbered list, academic style)
 */
function generatePublicationsSection(projects: ResumeData['projects']): string {
  if (!projects || projects.length === 0) return '';

  const entries = projects.map((project, index) => {
    let entry = `${index + 1}. `;

    if (project.url) {
      entry += `*${escapeTypst(project.name)}* #link("${project.url}")[\\[Link\\]]`;
    } else {
      entry += `*${escapeTypst(project.name)}*`;
    }

    entry += ` \\ ${escapeTypst(project.description)}`;

    if (project.highlights && project.highlights.length > 0) {
      entry += '\n' + project.highlights.map((h) => `  - ${escapeTypst(h)}`).join('\n');
    }

    return entry;
  });

  return `#cv-section("Research & Projects")

${entries.join('\n\n')}`;
}

/**
 * Generate skills section
 */
function generateSkillsSection(skills: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const groups = skills.map((skillGroup) => {
    const keywords = skillGroup.keywords.map((k) => escapeTypst(k)).join(', ');
    return `*${escapeTypst(skillGroup.name)}:* ${keywords}`;
  });

  return `#cv-section("Skills & Competencies")

${groups.join('\n\n')}`;
}

/**
 * Generate achievements section
 */
function generateAchievementsSection(achievements?: string[]): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map((a) => `- ${escapeTypst(a)}`).join('\n');

  return `#cv-section("Honors & Awards")

${items}`;
}

/**
 * Generate certifications section
 */
function generateCertificationsSection(certifications?: string[]): string {
  if (!certifications || certifications.length === 0) return '';

  const items = certifications.map((c) => `- ${escapeTypst(c)}`).join('\n');

  return `#cv-section("Certifications & Licenses")

${items}`;
}

/**
 * Generate references section
 */
function generateReferencesSection(references?: string): string {
  if (!references) return '';

  return `#cv-section("References")

${escapeTypst(references)}`;
}
