/**
 * Timeline Dual-Column Typst Generator
 * 50/50 symmetric layout with full-width header/footer and two-column body
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from '@/lib/typst/utils';

/**
 * Generate complete Timeline Dual-Column Typst code
 */
export function generateTimelineDual(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateSummary(data.basics.summary),
    generateTwoColumnBody(data),
    generateSkillsRow(data.skills),
    generateEducationRow(data.education),
    generateAchievementsRow(data.achievements),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with timeline styling
 */
function generatePreamble(): string {
  return `// Timeline Dual-Column Resume — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 1.5cm, right: 1.5cm, top: 1.5cm, bottom: 1.5cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 10pt,
  fill: rgb("#1f2937"),
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette (Orange/Blue timeline) —
#let timeline   = rgb("#f97316")
#let work-color = rgb("#3b82f6")
#let project-color = rgb("#8b5cf6")
#let text-primary = rgb("#1f2937")
#let text-secondary = rgb("#6b7280")

// — Reusable components —

#let cv-section(title) = {
  v(0.8em)
  text(size: 14pt, weight: "bold", fill: text-primary, upper(title))
  v(0.2em)
  line(length: 100%, stroke: 1.5pt + timeline)
  v(0.4em)
}

#let timeline-event(title, subtitle, date, location) = {
  v(0.3em)
  text(size: 11pt, weight: "bold", fill: text-primary, title)
  linebreak()
  text(style: "italic", fill: work-color, subtitle)
  linebreak()
  text(size: 9pt, fill: text-secondary)[#date • #location]
  v(0.4em)
}

#let project-event(title, description, url-text) = {
  v(0.3em)
  text(size: 11pt, weight: "bold", fill: text-primary, title)
  linebreak()
  text(size: 9pt, fill: project-color, description)
  if url-text != "" {
    linebreak()
    text(size: 9pt, fill: text-secondary, url-text)
  }
  v(0.4em)
}

#let cv-divider() = {
  v(0.4em)
  line(length: 100%, stroke: 0.5pt + timeline.lighten(70%))
  v(0.4em)
}`;
}

/**
 * Generate centered header
 */
function generateHeader(basics: ResumeData['basics']): string {
  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(
      `✉ #link("mailto:${basics.email}")[${escapeTypst(basics.email)}]`
    );
  }
  if (basics.phone) {
    contactParts.push(`☎ ${escapeTypst(basics.phone)}`);
  }
  if (basics.location) {
    contactParts.push(`📍 ${escapeTypst(basics.location)}`);
  }

  basics.profiles.forEach((profile) => {
    const icon = networkToIcon(profile.network);
    const label = cleanURL(profile.url);
    contactParts.push(
      `${icon} #link("${profile.url}")[${escapeTypst(label)}]`
    );
  });

  const contactLine = contactParts.join(' • ');

  return `// ── Header ──────────────────────────────────────────
#align(center)[
  #text(size: 24pt, weight: "bold", fill: text-primary)[${escapeTypst(basics.name)}]
  #linebreak()
  #v(4pt)
  #text(size: 14pt, fill: timeline)[${escapeTypst(basics.label)}]
  #v(8pt)
  #text(size: 9pt, fill: text-secondary)[${contactLine}]
]`;
}

/**
 * Generate summary section
 */
function generateSummary(summary?: string): string {
  if (!summary) return '';

  return `#cv-section("Professional Summary")
${escapeTypst(summary)}`;
}

/**
 * Generate two-column body: work (left) + projects (right)
 */
function generateTwoColumnBody(data: ResumeData): string {
  const leftColumn = generateExperienceColumn(data.work);
  const rightColumn = generateProjectsColumn(data.projects);

  if (!leftColumn && !rightColumn) return '';

  return `// ── Two-column body ─────────────────────────────────
#grid(
  columns: (50%, 50%),
  column-gutter: 1em,
  [
${leftColumn || '    // No work experience'}
  ],
  [
${rightColumn || '    // No projects'}
  ],
)`;
}

/**
 * Generate left column - work experience
 */
function generateExperienceColumn(work: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const lines: string[] = [];
  lines.push('    #text(size: 16pt, weight: "bold", fill: timeline)[Work Timeline]');
  lines.push('    #v(0.5em)');

  work.forEach((job, index) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);

    lines.push(`    #timeline-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`);

    if (job.highlights && job.highlights.length > 0) {
      const [description, ...bullets] = job.highlights;
      lines.push(`    ${escapeTypst(description)}`);
      if (bullets.length > 0) {
        bullets.forEach((b) => {
          lines.push(`    - ${escapeTypst(b)}`);
        });
      }
    }

    if (index < work.length - 1) {
      lines.push('    #cv-divider()');
    }
  });

  return lines.join('\n');
}

/**
 * Generate right column - projects
 */
function generateProjectsColumn(projects: ResumeData['projects']): string {
  if (!projects || projects.length === 0) return '';

  const lines: string[] = [];
  lines.push('    #text(size: 16pt, weight: "bold", fill: timeline)[Project Timeline]');
  lines.push('    #v(0.5em)');

  projects.forEach((project, index) => {
    const urlText = project.url ? escapeTypst(cleanURL(project.url)) : '';

    lines.push(`    #project-event("${escapeTypst(project.name)}", "${escapeTypst(project.description)}", "${urlText}")`);

    if (project.highlights && project.highlights.length > 0) {
      project.highlights.forEach((h) => {
        lines.push(`    - ${escapeTypst(h)}`);
      });
    }

    if (index < projects.length - 1) {
      lines.push('    #cv-divider()');
    }
  });

  return lines.join('\n');
}

/**
 * Generate skills row (full width)
 */
function generateSkillsRow(skills: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const entries = skills.map((skillGroup) => {
    const keywords = skillGroup.keywords.map((k) => escapeTypst(k)).join(' · ');
    return `*#text(fill: work-color)[${escapeTypst(skillGroup.name)}:]* ${keywords}`;
  });

  return `#cv-section("Technical Skills")

${entries.join('\n\n')}`;
}

/**
 * Generate education row (full width)
 */
function generateEducationRow(education: ResumeData['education']): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu) => {
    const degree = `${edu.studyType} of ${edu.area}`;
    const dateRange = formatDateRange(edu.startDate, edu.endDate);

    let content = `*${escapeTypst(degree)}* #h(1fr) _${dateRange}_
_#text(fill: project-color)[${escapeTypst(edu.institution)}]_ #h(1fr) ${escapeTypst(edu.location)}`;

    if (edu.note) {
      content += `\n#text(size: 9pt)[${escapeTypst(edu.note)}]`;
    }

    return content;
  });

  return `#cv-section("Education")

${entries.join('\n\n')}`;
}

/**
 * Generate achievements row (full width)
 */
function generateAchievementsRow(achievements: string[]): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map((a) => `- ${escapeTypst(a)}`).join('\n');

  return `#cv-section("Achievements & Recognition")

${items}`;
}
