/**
 * Awesome CV Typst Generator
 * Professional single-column resume inspired by posquit0's Awesome-CV
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from '@/lib/typst/utils';

/**
 * Generate complete Awesome CV Typst code
 */
export function generateAwesomeCV(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateSummary(data.basics.summary),
    generateExperienceSection(data.work),
    generateProjectsSection(data.projects),
    generateEducationSection(data.education),
    generateSkillsSection(data.skills),
    generateAchievementsSection(data.achievements),
    generateCertificationsSection(data.certifications),
    generateReferencesSection(data.references),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with Awesome-CV styling
 */
function generatePreamble(): string {
  return `// Awesome CV — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 2cm, right: 2cm, top: 1.5cm, bottom: 2cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 11pt,
  fill: rgb("#333333"),
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette (Awesome-CV inspired) —
#let awesome     = rgb("#DC3522")
#let darktext    = rgb("#414141")
#let text-color  = rgb("#333333")
#let graytext    = rgb("#5D5D5D")
#let lighttext   = rgb("#999999")

// — Reusable components —

#let cv-section(title) = {
  v(0.6em)
  text(size: 16pt, weight: "bold", fill: text-color, smallcaps(title))
  v(0.2em)
  line(length: 100%, stroke: 1.5pt + awesome)
  v(0.4em)
}

#let cv-entry(title, subtitle, date, location) = {
  v(0.3em)
  grid(
    columns: (1fr, auto),
    text(weight: "bold", fill: darktext, title),
    text(size: 9pt, style: "italic", fill: graytext, date),
  )
  grid(
    columns: (1fr, auto),
    text(fill: graytext, smallcaps(subtitle)),
    text(size: 9pt, style: "italic", fill: awesome, location),
  )
  v(0.3em)
}

#let cv-divider() = {
  v(0.4em)
}

#let cv-paragraph(body) = {
  text(size: 9pt, fill: text-color, body)
}`;
}

/**
 * Generate header section mimicking Awesome-CV's makecvheader
 */
function generateHeader(basics: ResumeData['basics']): string {
  const nameParts = basics.name.split(' ');
  const firstName = nameParts.slice(0, -1).join(' ') || nameParts[0];
  const lastName = nameParts[nameParts.length - 1];

  const contactParts: string[] = [];

  if (basics.location) {
    contactParts.push(`📍 ${escapeTypst(basics.location)}`);
  }
  if (basics.phone) {
    contactParts.push(`📱 ${escapeTypst(basics.phone)}`);
  }
  if (basics.email) {
    contactParts.push(
      `✉ #link("mailto:${basics.email}")[${escapeTypst(basics.email)}]`
    );
  }

  const socialParts: string[] = [];
  basics.profiles.forEach((profile) => {
    const icon = networkToIcon(profile.network);
    const label = profile.label || cleanURL(profile.url);
    socialParts.push(
      `${icon} #link("${profile.url}")[${escapeTypst(label)}]`
    );
  });

  const contactLine = contactParts.join('  |  ');
  const socialLine = socialParts.length > 0 ? socialParts.join('  |  ') : '';

  let header = `// ── Header ──────────────────────────────────────────
#align(center)[
  #text(size: 32pt, fill: graytext)[${escapeTypst(firstName)} ]#text(size: 32pt, weight: "bold", fill: text-color)[${escapeTypst(lastName)}]
  #v(2pt)
  #text(size: 8pt, fill: awesome, smallcaps[${escapeTypst(basics.label)}])
  #v(4pt)
  #text(size: 8pt, fill: text-color)[${contactLine}]`;

  if (socialLine) {
    header += `
  #v(2pt)
  #text(size: 7pt, fill: text-color)[${socialLine}]`;
  }

  header += '\n]';

  return header;
}

/**
 * Generate summary section
 */
function generateSummary(summary?: string): string {
  if (!summary) return '';

  return `#cv-section("Summary")
#cv-paragraph[${escapeTypst(summary)}]`;
}

/**
 * Generate work experience section
 */
function generateExperienceSection(work: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const entries = work.map((job) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);
    const subtitle = `${escapeTypst(job.company)} — ${escapeTypst(job.type)}`;

    let content = `#cv-entry("${escapeTypst(job.position)}", "${subtitle}", "${dateRange}", "${escapeTypst(job.location)}")`;

    if (job.highlights && job.highlights.length > 0) {
      content += '\n' + job.highlights.map((h) => `- ${escapeTypst(h)}`).join('\n');
    }

    content += '\n#cv-divider()';

    return content;
  });

  return `#cv-section("Work Experience")

${entries.join('\n\n')}`;
}

/**
 * Generate projects section
 */
function generateProjectsSection(projects: ResumeData['projects']): string {
  if (!projects || projects.length === 0) return '';

  const entries = projects.map((project) => {
    let header = `*#text(fill: darktext)[${escapeTypst(project.name)}]* — _#text(fill: graytext)[${escapeTypst(project.description)}]_`;

    if (project.url) {
      header += ` #text(fill: awesome)[\\[] #link("${project.url}")[Link] #text(fill: awesome)[\\]]`;
    }

    let content = header;

    if (project.highlights && project.highlights.length > 0) {
      content += '\n' + project.highlights.map((h) => `- ${escapeTypst(h)}`).join('\n');
    }

    content += '\n#cv-divider()';

    return content;
  });

  return `#cv-section("Projects")

${entries.join('\n\n')}`;
}

/**
 * Generate education section
 */
function generateEducationSection(education: ResumeData['education']): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu) => {
    const dateRange = formatDateRange(edu.startDate, edu.endDate);
    const degree = `${edu.studyType} of ${edu.area}`;

    let content = `#cv-entry("${escapeTypst(degree)}", "${escapeTypst(edu.institution)}", "${dateRange}", "${escapeTypst(edu.location)}")`;

    if (edu.note) {
      content += `\n#text(size: 9pt, fill: text-color)[${escapeTypst(edu.note)}]`;
    }

    content += '\n#cv-divider()';

    return content;
  });

  return `#cv-section("Education")

${entries.join('\n\n')}`;
}

/**
 * Generate skills section with tabular layout
 */
function generateSkillsSection(skills: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const entries = skills.map((skill) => {
    const keywords = skill.keywords.map((k) => escapeTypst(k)).join(', ');
    return `*#text(fill: darktext)[${escapeTypst(skill.name)}]* #h(1em) #text(fill: text-color)[${keywords}]`;
  });

  return `#cv-section("Skills")

${entries.join('\n\n')}`;
}

/**
 * Generate achievements section
 */
function generateAchievementsSection(achievements: string[]): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map((a) => `- ${escapeTypst(a)}`).join('\n');

  return `#cv-section("Honors & Awards")

${items}`;
}

/**
 * Generate certifications section
 */
function generateCertificationsSection(certifications: string[]): string {
  if (!certifications || certifications.length === 0) return '';

  const items = certifications.map((c) => `- ${escapeTypst(c)}`).join('\n');

  return `#cv-section("Certificates")

${items}`;
}

/**
 * Generate references section
 */
function generateReferencesSection(references?: string): string {
  if (!references) return '';

  return `#cv-section("References")
#cv-paragraph[${escapeTypst(references)}]`;
}
