/**
 * Creative Portfolio Typst Generator
 * Single-column layout with creative purple/pink styling and colored header banner
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from '@/lib/typst/utils';

/**
 * Generate complete Creative Portfolio Typst code
 */
export function generateCreativePortfolio(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateHeader(data.basics),
    generateSummary(data.basics.summary),
    generateSkillsSection(data.skills),
    generateExperienceSection(data.work),
    generateProjectsSection(data.projects),
    generateEducationSection(data.education),
    generateAchievementsSection(data.achievements),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with creative styling
 */
function generatePreamble(): string {
  return `// Creative Portfolio — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 1.5cm, right: 1.5cm, top: 4.5cm, bottom: 2cm),
  numbering: "1",
  background: place(top, rect(width: 100%, height: 4cm, fill: rgb("#7c3aed"))) + place(top + left, dy: 4cm, rect(width: 100%, height: 0.5cm, fill: rgb("#ec4899"))),
)

#set text(
  font: "Linux Libertine",
  size: 10pt,
  fill: rgb("#1f2937"),
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette (Creative: purple + pink) —
#let purple  = rgb("#7c3aed")
#let pink    = rgb("#ec4899")
#let light-purple = rgb("#c4b5fd")
#let main-text = rgb("#1f2937")
#let secondary-text = rgb("#6b7280")

// — Reusable components —

#let cv-section(title) = {
  v(0.8em)
  text(size: 14pt, weight: "bold", fill: purple, title)
  v(0.2em)
  line(length: 100%, stroke: 2pt + pink)
  v(0.4em)
}

#let cv-event(title, subtitle, date, location) = {
  v(0.3em)
  grid(
    columns: (1fr, auto),
    text(size: 12pt, weight: "bold", fill: purple, title),
    text(size: 9pt, style: "italic", fill: secondary-text, date),
  )
  grid(
    columns: (1fr, auto),
    text(style: "italic", fill: secondary-text, subtitle),
    text(size: 9pt, fill: secondary-text, location),
  )
  v(0.4em)
}

#let cv-tag(keyword) = {
  box(
    inset: (x: 5pt, y: 3pt),
    radius: 3pt,
    stroke: 0.5pt + purple,
    fill: purple.lighten(85%),
    text(size: 9pt, weight: "bold", fill: purple, keyword),
  )
  h(3pt)
}

#let cv-divider() = {
  v(0.6em)
}`;
}

/**
 * Generate creative header with name on banner background
 */
function generateHeader(basics: ResumeData['basics']): string {
  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(
      `#link("mailto:${basics.email}")[✉ ${escapeTypst(basics.email)}]`
    );
  }
  if (basics.phone) {
    contactParts.push(`☎ ${escapeTypst(basics.phone)}`);
  }
  if (basics.location) {
    contactParts.push(`📍 ${escapeTypst(basics.location)}`);
  }

  basics.profiles?.forEach((profile) => {
    if (profile.network && profile.url) {
      const icon = networkToIcon(profile.network);
      const displayText = profile.label || cleanURL(profile.url);
      contactParts.push(
        `#link("${profile.url}")[${icon} ${escapeTypst(displayText)}]`
      );
    }
  });

  const contactLine = contactParts.join('  #text(fill: light-purple)[ • ]  ');

  return `// ── Header (overlays the purple banner) ─────────────
#place(top + center, dy: -3.5cm)[
  #text(size: 28pt, weight: "bold", fill: white)[${escapeTypst(basics.name)}]
  #linebreak()
  #v(8pt)
  #text(size: 14pt, fill: white)[${escapeTypst(basics.label)}]
  #v(12pt)
  #text(size: 9pt, fill: white)[${contactLine}]
]`;
}

/**
 * Generate summary section
 */
function generateSummary(summary?: string): string {
  if (!summary) return '';

  return `#cv-section("About Me")
${escapeTypst(summary)}`;
}

/**
 * Generate skills section with tag cloud
 */
function generateSkillsSection(skills?: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const groups = skills.map((skillGroup) => {
    const tags = skillGroup.keywords
      .map((kw) => `#cv-tag("${escapeTypst(kw)}")`)
      .join(' ');
    return `*#text(fill: purple)[${escapeTypst(skillGroup.name)}:]*  ${tags}`;
  });

  return `#cv-section("Skills")

${groups.join('\n\n')}`;
}

/**
 * Generate experience section
 */
function generateExperienceSection(work?: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const entries = work.map((job) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);

    let content = `#cv-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

    if (job.highlights && job.highlights.length > 0) {
      content += '\n' + job.highlights.map((h) => `- ${escapeTypst(h)}`).join('\n');
    }

    return content;
  });

  return `#cv-section("Professional Experience")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate projects section
 */
function generateProjectsSection(projects?: ResumeData['projects']): string {
  if (!projects || projects.length === 0) return '';

  const entries = projects.map((project) => {
    let header = `*#text(size: 12pt, fill: purple)[${escapeTypst(project.name)}]*`;
    if (project.url) {
      header = `#link("${project.url}")[${header}]`;
    }

    let content = header;

    if (project.description) {
      content += `\n#text(fill: secondary-text)[${escapeTypst(project.description)}]`;
    }

    if (project.highlights && project.highlights.length > 0) {
      content += '\n' + project.highlights.map((h) => `- ${escapeTypst(h)}`).join('\n');
    }

    return content;
  });

  return `#cv-section("Featured Projects")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate education section
 */
function generateEducationSection(education?: ResumeData['education']): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu) => {
    const degree = `${edu.studyType} in ${edu.area}`;
    const dateRange = formatDateRange(edu.startDate, edu.endDate);

    let content = `*#text(size: 12pt, fill: purple)[${escapeTypst(degree)}]*
_${escapeTypst(edu.institution)}_ #h(1fr) #text(fill: secondary-text)[${dateRange}]`;

    if (edu.location) {
      content += `\n#text(fill: secondary-text)[${escapeTypst(edu.location)}]`;
    }

    const details: string[] = [];
    if (edu.gpa) {
      details.push(`GPA: ${escapeTypst(edu.gpa)}`);
    }
    if (edu.note) {
      details.push(escapeTypst(edu.note));
    }

    if (details.length > 0) {
      content += `\n#text(fill: secondary-text)[${details.join(' | ')}]`;
    }

    return content;
  });

  return `#cv-section("Education")

${entries.join('\n\n#cv-divider()\n\n')}`;
}

/**
 * Generate achievements section
 */
function generateAchievementsSection(achievements?: ResumeData['achievements']): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map((a) => `- ${escapeTypst(a)}`).join('\n');

  return `#cv-section("Awards & Recognition")

${items}`;
}
