/**
 * LaTeX Resume Generator
 * Converts ResumeData to custom two-column LaTeX resume using standard packages
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeLaTeX,
  formatDateRange,
  arrayToCompactItemize,
  cleanURL,
  escapeURL,
} from './utils';

/**
 * Generate complete LaTeX code from resume data
 */
export function generateLatexCode(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    '\\begin{document}',
    '',
    generateHeader(data.basics),
    '',
    '% Start two-column layout',
    '\\columnratio{0.6}',
    '\\setlength{\\columnsep}{1.5em}',
    '\\begin{paracol}{2}',
    '',
    '% LEFT COLUMN - Main Content',
    generateSummary(data.basics.summary),
    generateExperienceSection(data.work),
    generateProjectsSection(data.projects),
    '',
    '% Switch to RIGHT COLUMN - Sidebar',
    '\\switchcolumn',
    '',
    generateEducationSection(data.education),
    generateSkillsSection(data.skills),
    generateAchievementsSection(data.achievements),
    generateCertificationsSection(data.certifications),
    generateReferencesSection(data.references),
    '',
    '\\end{paracol}',
    '\\end{document}',
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate LaTeX preamble (document class and packages)
 */
function generatePreamble(): string {
  return `% LaTeX Resume - Generated by Easy Resume
% Compile with pdflatex or xelatex
% Custom two-column layout using standard packages

\\documentclass[10pt,a4paper]{article}

% Page layout
\\usepackage[left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm]{geometry}

% Fonts and text formatting
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{lmodern}
\\usepackage{microtype}

% Colors
\\usepackage[dvipsnames]{xcolor}
\\definecolor{PrimaryColor}{HTML}{0E5484}
\\definecolor{AccentColor}{HTML}{2E86AB}
\\definecolor{TextColor}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}

% Icons (FontAwesome)
\\usepackage{fontawesome5}

% Links
\\usepackage{hyperref}
\\hypersetup{
    colorlinks=true,
    linkcolor=AccentColor,
    urlcolor=AccentColor,
    pdftitle={Resume},
    pdfauthor={Easy Resume}
}

% Two-column layout
\\usepackage{paracol}

% Lists
\\usepackage{enumitem}
\\setlist{nosep,leftmargin=*}
\\setlist[itemize]{label=\\textbullet,itemsep=0.1em,parsep=0em,topsep=0.3em}

% Section formatting
\\usepackage{titlesec}
\\titleformat{\\section}
  {\\color{PrimaryColor}\\Large\\bfseries\\uppercase}
  {}{0em}{}[\\color{AccentColor}\\titlerule]
\\titlespacing*{\\section}{0pt}{1.5ex}{1ex}

\\titleformat{\\subsection}
  {\\color{TextColor}\\large\\bfseries}
  {}{0em}{}
\\titlespacing*{\\subsection}{0pt}{1ex}{0.5ex}

% Remove page numbers
\\pagestyle{empty}

% Paragraph settings
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{0.3em}

% Consistent line spacing
\\linespread{1.1}
\\selectfont

% Custom commands for resume elements
\\newcommand{\\cvname}[1]{%
  {\\Huge\\bfseries\\color{TextColor}#1}\\par\\vspace{0.3em}%
}

\\newcommand{\\cvtitle}[1]{%
  {\\large\\color{PrimaryColor}#1}\\par\\vspace{0.8em}%
}

\\newcommand{\\cvcontact}[1]{%
  {\\small\\color{LightGrey}#1}
}

% CV event with consistent spacing - uses strut for uniform line height
\\newcommand{\\cvevent}[4]{%
  \\par\\vspace{0.3em}%
  {\\strut\\textbf{\\color{TextColor}#1}}\\par\\nobreak%
  \\vspace{0.15em}%
  {\\strut\\color{PrimaryColor}\\textit{#2}}\\par\\nobreak%
  \\vspace{0.15em}%
  {\\strut\\small\\color{LightGrey}#3 \\textbar\\ #4}\\par%
  \\vspace{0.6em}%
}

\\newcommand{\\cvdivider}{%
  \\vspace{0.6em}%
  {\\color{AccentColor!30}\\hrule}%
  \\vspace{0.6em}%
}

% Skill tag with fixed height box for consistent alignment
\\newcommand{\\cvtag}[1]{%
  \\mbox{\\colorbox{AccentColor!15}{\\rule{0pt}{1.1em}\\color{TextColor}\\small\\textbf{#1}}}\\hspace{0.1em}%
}

% Subsection for skills with consistent baseline
\\newcommand{\\cvsubsection}[1]{%
  \\par\\vspace{0.8em}%
  {\\rule{0pt}{1.2em}\\color{PrimaryColor}\\textbf{\\uppercase{#1}}}\\par\\nobreak%
  \\vspace{0.3em}%
}`;
}

/**
 * Generate header with personal information
 * Two-column layout: left (name & title), right (contact info)
 */
function generateHeader(basics: ResumeData['basics']): string {
  const lines: string[] = ['% Header'];

  // Start two-column header layout using minipage
  lines.push('\\begin{minipage}[t]{0.55\\textwidth}');
  lines.push(`\\cvname{${escapeLaTeX(basics.name)}}`);
  lines.push(`\\cvtitle{${escapeLaTeX(basics.label)}}`);
  lines.push('\\end{minipage}%');
  lines.push('\\hfill');
  lines.push('\\begin{minipage}[t]{0.4\\textwidth}');
  lines.push('\\raggedright');
  lines.push('\\cvcontact{');

  const contactParts: string[] = [];

  if (basics.email) {
    contactParts.push(`  \\faEnvelope\\ \\href{mailto:${basics.email}}{${basics.email}}`);
  }

  if (basics.phone) {
    contactParts.push(`  \\faPhone\\ ${escapeLaTeX(basics.phone)}`);
  }

  if (basics.location) {
    contactParts.push(`  \\faMapMarker\\ ${escapeLaTeX(basics.location)}`);
  }

  // Add social profiles
  basics.profiles.forEach((profile) => {
    const cleanUrl = cleanURL(profile.url);
    const label = profile.label || cleanUrl;

    if (profile.network.toLowerCase() === 'linkedin') {
      contactParts.push(`  \\faLinkedin\\ \\href{${escapeURL(profile.url)}}{${escapeLaTeX(label)}}`);
    } else if (profile.network.toLowerCase() === 'github') {
      contactParts.push(`  \\faGithub\\ \\href{${escapeURL(profile.url)}}{${escapeLaTeX(label)}}`);
    } else {
      contactParts.push(`  \\faGlobe\\ \\href{${escapeURL(profile.url)}}{${escapeLaTeX(label)}}`);
    }
  });

  // Stack contact info vertically with line breaks
  lines.push(contactParts.join('\\\\\n'));
  lines.push('}');
  lines.push('\\end{minipage}');
  lines.push('');
  lines.push('\\vspace{1em}');
  lines.push('{\\color{AccentColor}\\hrule height 2pt}');
  lines.push('\\vspace{1em}');

  return lines.join('\n');
}

/**
 * Generate summary/introduction section
 */
function generateSummary(summary?: string): string {
  if (!summary) return '';

  // Escape LaTeX and add \noindent before each paragraph to prevent indentation
  const escapedSummary = escapeLaTeX(summary);
  // Replace paragraph breaks with \noindent command
  const formattedSummary = escapedSummary.replace(/\n\n/g, '\n\n\\noindent ');

  return `\\section{Introduction}

\\noindent ${formattedSummary}`;
}

/**
 * Generate education section (for RIGHT column)
 * Includes consistent spacing between entries
 */
function generateEducationSection(education: ResumeData['education']): string {
  if (!education || education.length === 0) return '';

  const entries = education.map((edu, index) => {
    const dateRange = formatDateRange(edu.startDate, edu.endDate);
    const degree = `${edu.studyType} of ${edu.area}`;

    // Add note with consistent spacing
    const detailsStr = edu.note ? `\\vspace{0.3em}\n{\\small\\strut ${escapeLaTeX(edu.note)}}` : '';

    const divider = index < education.length - 1 ? '\n\\cvdivider' : '';

    return `\\cvevent{${escapeLaTeX(degree)}}{${escapeLaTeX(edu.institution)}}{${dateRange}}{${escapeLaTeX(edu.location)}}${detailsStr}${divider}`;
  });

  return `\\section{Education}

${entries.join('\n\n')}`;
}

/**
 * Generate work experience section (for LEFT column)
 * Uses consistent spacing between job entries and content
 */
function generateExperienceSection(work: ResumeData['work']): string {
  if (!work || work.length === 0) return '';

  const entries = work.map((job, index) => {
    const dateRange = formatDateRange(job.startDate, job.endDate);

    // First highlight is description paragraph, rest are bullet points
    let content = '';
    if (job.highlights && job.highlights.length > 0) {
      const [description, ...bulletPoints] = job.highlights;
      // Add consistent spacing before description
      content = '\n\\vspace{0.2em}\\noindent ' + escapeLaTeX(description);
      if (bulletPoints.length > 0) {
        content += '\n\\vspace{0.2em}\n' + arrayToCompactItemize(bulletPoints);
      }
    }

    const divider = index < work.length - 1 ? '\n\\cvdivider' : '';

    return `\\cvevent{${escapeLaTeX(job.position)}}{${escapeLaTeX(job.company)} — ${escapeLaTeX(job.type)}}{${dateRange}}{${escapeLaTeX(job.location)}}${content}${divider}`;
  });

  return `\\section{Experience}

${entries.join('\n\n')}`;
}

/**
 * Generate projects section (for LEFT column)
 * 2x2 grid layout for projects
 */
function generateProjectsSection(projects: ResumeData['projects']): string {
  if (!projects || projects.length === 0) return '';

  // Generate individual project cells
  const generateProjectCell = (project: ResumeData['projects'][0]) => {
    const projectTitle = `\\textbf{\\color{TextColor}${escapeLaTeX(project.name)} — ${escapeLaTeX(project.description)}}`;

    // Display highlights as paragraph text without bullet points
    // Add \noindent to prevent paragraph indentation
    const highlights = project.highlights && project.highlights.length > 0
      ? '\n\n\\noindent ' + project.highlights.map(h => escapeLaTeX(h)).join(' ')
      : '';

    return `${projectTitle}${highlights}`;
  };

  // Create 2x2 grid using minipage
  const gridRows: string[] = [];

  for (let i = 0; i < projects.length; i += 2) {
    const leftProject = projects[i];
    const rightProject = projects[i + 1];

    const leftCell = `\\begin{minipage}[t]{0.48\\linewidth}
${generateProjectCell(leftProject)}
\\end{minipage}`;

    const rightCell = rightProject
      ? `\\begin{minipage}[t]{0.48\\linewidth}
${generateProjectCell(rightProject)}
\\end{minipage}`
      : '';

    gridRows.push(`${leftCell}%
\\hfill
${rightCell}`);
  }

  return `\\section{Recent Projects / Open-Source}

${gridRows.join('\n\n\\vspace{1em}\n\n')}

\\vspace{1em}

{\\small\\textit{Explore 50+ additional open-source projects on \\href{https://github.com/ChanMeng666}{my GitHub}.}}`;
}

/**
 * Generate skills section (for RIGHT column)
 * Uses consistent spacing for skill categories and tags
 * Each skill category uses a fixed line height environment for alignment
 */
function generateSkillsSection(skills: ResumeData['skills']): string {
  if (!skills || skills.length === 0) return '';

  const entries = skills.map((skill) => {
    const tags = skill.keywords.map(keyword => `\\cvtag{${escapeLaTeX(keyword)}}`).join('');
    // Use a minipage with fixed baselineskip to ensure consistent tag row heights
    return `\\cvsubsection{${escapeLaTeX(skill.name)}}
\\begingroup
\\setlength{\\baselineskip}{1.8em}%
\\setlength{\\lineskiplimit}{0pt}%
\\setlength{\\lineskip}{0.5em}%
\\noindent\\raggedright%
${tags}%
\\par
\\endgroup`;
  });

  return `\\section{Skills}

${entries.join('\n\n')}`;
}

/**
 * Generate achievements section (for RIGHT column)
 */
function generateAchievementsSection(achievements: string[]): string {
  if (!achievements || achievements.length === 0) return '';

  const items = achievements.map(achievement => `  \\item ${escapeLaTeX(achievement)}`).join('\n');

  return `\\section{Achievements \\& Communities}

\\begin{itemize}
${items}
\\end{itemize}`;
}

/**
 * Generate certifications section (for RIGHT column)
 */
function generateCertificationsSection(certifications: string[]): string {
  if (!certifications || certifications.length === 0) return '';

  // Group certifications by category
  const coreDevCerts: string[] = [];
  const frameworkCerts: string[] = [];
  const databaseCerts: string[] = [];
  const toolsCerts: string[] = [];
  const otherCerts: string[] = [];

  certifications.forEach(cert => {
    const lowerCert = cert.toLowerCase();
    if (lowerCert.includes('frontend') || lowerCert.includes('software engineer') || lowerCert.includes('problem solving')) {
      coreDevCerts.push(cert);
    } else if (lowerCert.includes('react') || lowerCert.includes('angular') || lowerCert.includes('node') || lowerCert.includes('javascript') || lowerCert.includes('java') || lowerCert.includes('go')) {
      frameworkCerts.push(cert);
    } else if (lowerCert.includes('sql') || lowerCert.includes('data') || lowerCert.includes('rest api')) {
      databaseCerts.push(cert);
    } else if (lowerCert.includes('github') || lowerCert.includes('docker') || lowerCert.includes('ubuntu') || lowerCert.includes('agile') || lowerCert.includes('system') || lowerCert.includes('project') || lowerCert.includes('cyber')) {
      toolsCerts.push(cert);
    } else {
      otherCerts.push(cert);
    }
  });

  const sections: string[] = [];

  if (coreDevCerts.length > 0) {
    sections.push(`\\cvsubsection{Core Development}
\\begin{itemize}
${coreDevCerts.map(c => `  \\item ${escapeLaTeX(c)}`).join('\n')}
\\end{itemize}`);
  }

  if (frameworkCerts.length > 0) {
    sections.push(`\\cvsubsection{Frameworks \\& Languages}
\\begin{itemize}
${frameworkCerts.map(c => `  \\item ${escapeLaTeX(c)}`).join('\n')}
\\end{itemize}`);
  }

  if (databaseCerts.length > 0) {
    sections.push(`\\cvsubsection{Database \\& API}
\\begin{itemize}
${databaseCerts.map(c => `  \\item ${escapeLaTeX(c)}`).join('\n')}
\\end{itemize}`);
  }

  if (toolsCerts.length > 0) {
    sections.push(`\\cvsubsection{Development Tools \\& Practices}
\\begin{itemize}
${toolsCerts.map(c => `  \\item ${escapeLaTeX(c)}`).join('\n')}
\\end{itemize}`);
  }

  if (otherCerts.length > 0) {
    sections.push(`\\begin{itemize}
${otherCerts.map(c => `  \\item ${escapeLaTeX(c)}`).join('\n')}
\\end{itemize}`);
  }

  return `\\section{Certifications}

${sections.join('\n\n')}`;
}

/**
 * Generate references section (for RIGHT column)
 */
function generateReferencesSection(references?: string): string {
  if (!references) return '';

  // Escape LaTeX and add \noindent before each paragraph to prevent indentation
  const escapedReferences = escapeLaTeX(references);
  const formattedReferences = escapedReferences.replace(/\n\n/g, '\n\n\\noindent ');

  return `\\section{References}

\\noindent ${formattedReferences}`;
}
