/**
 * Sidebar Accent Typst Generator
 * 30% colored sidebar + 70% main content layout
 */

import { ResumeData } from '@/lib/validation/schema';
import {
  escapeTypst,
  formatDateRange,
  cleanURL,
  networkToIcon,
} from '@/lib/typst/utils';

/**
 * Generate complete Sidebar Accent Typst code
 */
export function generateSidebarAccent(data: ResumeData): string {
  const sections = [
    generatePreamble(),
    generateLayout(data),
  ];

  return sections.filter(Boolean).join('\n\n');
}

/**
 * Generate Typst preamble with sidebar styling
 */
function generatePreamble(): string {
  return `// Sidebar Accent Resume — Generated by Vitex
// Compile with: typst compile resume.typ

#set page(
  paper: "a4",
  margin: (left: 0cm, right: 0cm, top: 0cm, bottom: 0cm),
  numbering: none,
)

#set text(
  font: "Linux Libertine",
  size: 10pt,
  fill: rgb("#1f2937"),
  lang: "en",
)

#set par(
  leading: 0.65em,
  justify: false,
)

// — Color palette (Teal sidebar) —
#let sidebar-bg   = rgb("#0d9488")
#let sidebar-text = white
#let main-accent  = rgb("#0891b2")
#let text-primary = rgb("#1f2937")
#let text-secondary = rgb("#6b7280")

// — Reusable components —

#let cv-section(title) = {
  v(0.8em)
  text(size: 13pt, weight: "bold", fill: main-accent, upper(title))
  v(0.2em)
  line(length: 100%, stroke: 1.5pt + main-accent)
  v(0.4em)
}

#let sidebar-section(title) = {
  v(0.8em)
  text(size: 11pt, weight: "bold", fill: sidebar-text, upper(title))
  v(0.3em)
}

#let cv-event(title, subtitle, date, location) = {
  v(0.3em)
  grid(
    columns: (1fr, auto),
    text(size: 11pt, weight: "bold", fill: text-primary, title),
    text(size: 9pt, style: "italic", fill: text-secondary, date),
  )
  grid(
    columns: (1fr, auto),
    text(style: "italic", fill: main-accent, subtitle),
    text(size: 9pt, fill: text-secondary, location),
  )
  v(0.4em)
}

#let cv-divider() = {
  v(0.5em)
}`;
}

/**
 * Generate the two-column layout with sidebar
 */
function generateLayout(data: ResumeData): string {
  const sidebar = generateSidebar(data);
  const mainContent = generateMainContent(data);

  return `// ── Layout ──────────────────────────────────────────
#grid(
  columns: (30%, 70%),
  // LEFT SIDEBAR
  rect(
    width: 100%,
    height: 100%,
    fill: sidebar-bg,
    inset: (x: 0.8cm, y: 1cm),
  )[
    #set text(fill: sidebar-text)
${sidebar}
  ],
  // RIGHT MAIN CONTENT
  rect(
    width: 100%,
    height: 100%,
    fill: white,
    inset: (x: 1cm, y: 1cm),
  )[
${mainContent}
  ],
)`;
}

/**
 * Generate sidebar content
 */
function generateSidebar(data: ResumeData): string {
  const parts: string[] = [];

  // Name and title
  parts.push(`    #align(center)[
      #text(size: 18pt, weight: "bold", fill: sidebar-text)[${escapeTypst(data.basics.name)}]
      #linebreak()
      #v(4pt)
      #text(size: 10pt, fill: sidebar-text.darken(10%))[${escapeTypst(data.basics.label)}]
    ]
    #v(1cm)`);

  // Contact
  const contactLines: string[] = [];
  if (data.basics.email) {
    contactLines.push(`    ✉ #text(size: 9pt)[${escapeTypst(data.basics.email)}]`);
  }
  if (data.basics.phone) {
    contactLines.push(`    ☎ #text(size: 9pt)[${escapeTypst(data.basics.phone)}]`);
  }
  if (data.basics.location) {
    contactLines.push(`    📍 #text(size: 9pt)[${escapeTypst(data.basics.location)}]`);
  }

  data.basics.profiles.forEach((profile) => {
    const icon = networkToIcon(profile.network);
    const label = cleanURL(profile.url);
    contactLines.push(`    ${icon} #text(size: 9pt)[${escapeTypst(label)}]`);
  });

  parts.push(`    #sidebar-section("Contact")
${contactLines.join(' \\\\\n')}
    #v(0.5cm)`);

  // Skills
  if (data.skills && data.skills.length > 0) {
    const skillLines: string[] = [];
    data.skills.forEach((skillGroup) => {
      skillLines.push(`    *${escapeTypst(skillGroup.name)}*`);
      skillGroup.keywords.forEach((keyword) => {
        skillLines.push(`    • ${escapeTypst(keyword)}`);
      });
      skillLines.push('    #v(4pt)');
    });

    parts.push(`    #sidebar-section("Skills")
${skillLines.join('\n')}
    #v(0.5cm)`);
  }

  // Education
  if (data.education && data.education.length > 0) {
    const eduLines: string[] = [];
    data.education.forEach((edu) => {
      const degree = `${edu.studyType} of ${edu.area}`;
      const dateRange = formatDateRange(edu.startDate, edu.endDate);
      eduLines.push(`    *${escapeTypst(degree)}*
    #text(size: 9pt)[${escapeTypst(edu.institution)}]
    #text(size: 8pt, fill: sidebar-text.darken(20%))[${dateRange}]
    #v(6pt)`);
    });

    parts.push(`    #sidebar-section("Education")
${eduLines.join('\n')}`);
  }

  return parts.join('\n\n');
}

/**
 * Generate main content area
 */
function generateMainContent(data: ResumeData): string {
  const sections: string[] = [];

  // Summary
  if (data.basics.summary) {
    sections.push(`    #cv-section("Professional Summary")
    ${escapeTypst(data.basics.summary)}`);
  }

  // Experience
  if (data.work && data.work.length > 0) {
    const entries = data.work.map((job, index) => {
      const dateRange = formatDateRange(job.startDate, job.endDate);

      let content = `    #cv-event("${escapeTypst(job.position)}", "${escapeTypst(job.company)}", "${dateRange}", "${escapeTypst(job.location)}")`;

      if (job.highlights && job.highlights.length > 0) {
        const [description, ...bullets] = job.highlights;
        content += `\n    ${escapeTypst(description)}`;
        if (bullets.length > 0) {
          content += '\n' + bullets.map((b) => `    - ${escapeTypst(b)}`).join('\n');
        }
      }

      if (index < data.work.length - 1) {
        content += '\n    #cv-divider()';
      }

      return content;
    });

    sections.push(`    #cv-section("Work Experience")

${entries.join('\n\n')}`);
  }

  // Projects
  if (data.projects && data.projects.length > 0) {
    const entries = data.projects.map((project, index) => {
      let content = `    *${escapeTypst(project.name)}* — ${escapeTypst(project.description)}`;

      if (project.highlights && project.highlights.length > 0) {
        content += '\n' + project.highlights.map((h) => `    - ${escapeTypst(h)}`).join('\n');
      }

      if (index < data.projects.length - 1) {
        content += '\n    #cv-divider()';
      }

      return content;
    });

    sections.push(`    #cv-section("Projects")

${entries.join('\n\n')}`);
  }

  // Achievements
  if (data.achievements && data.achievements.length > 0) {
    const items = data.achievements.map((a) => `    - ${escapeTypst(a)}`).join('\n');
    sections.push(`    #cv-section("Achievements")

${items}`);
  }

  // Certifications
  if (data.certifications && data.certifications.length > 0) {
    const items = data.certifications.map((c) => `    - ${escapeTypst(c)}`).join('\n');
    sections.push(`    #cv-section("Certifications")

${items}`);
  }

  return sections.join('\n\n');
}
